### ISSUE TITLE
Ini Settings Are Being Ignored

### ISSUE THREAD

**Issue by CharlesLove** [mrchrisster/MiSTer_SAM#1]
It might be more, but corelist, ignorezip, and (potentially) disablebootrom options are defaulting to their value in the original .sh file instead of using their changed .ini values.

**Comment by mrchrisster** [comment]
Thanks for reporting. Just noticed the issue myself actually. We might parse the ini too early before system is fully loaded

**Comment by mrchrisster** [comment]
Please run `MiSTer_SAM_on.sh` to update to the new version. Issue should be fixed now

**Comment by CharlesLove** [comment]
Awesome. Running it right now. I'll let it continue for a bit and see if everything is running correctly.

**Comment by mrchrisster** [comment]
Awesome thanks for the feedback. I'll close the issue now
