### ISSUE TITLE
SAM issues (zero functionality)

### ISSUE THREAD

**Issue by wyrfxrssn** [mrchrisster/MiSTer_SAM#101]
When all cores are installed on my SD Card, SAM exclusively launches cores that are not listed in the compatibility list (and which are not listed in the ini settings file). having deleted every unused core in an attempt to avoid this, I've found that SAM will attempt to launch a game three times, throw an error every time, and eventually quit.
First it prints this line about a thousand times:
"xargs: printf: terminated by signal 13"
Then it prints this error message:
"ERROR: Failed 1/2/3 times. No valid game found for core: gba rom:
  Trying to find another rom..."
If I change the settings ini so it only has one available core, after three of those error messages it just gives me a fatal error: no available cores (or something to that effect).
I've adjusted just about every setting in the ini file, updated my MiSTer, and have reinstalled MiSTer SAM several times, and nothing has ever worked. I know a few other people who also have had no luck getting SAM to work - unsure if their issues are the same as mine, but we all REALLY want to be able to use SAM if possible (especially cuz other folks we know had no issue getting SAM working). I appreciate the help!

**Comment by 0x15e** [comment]
I'm experiencing the same issue. I went through and verified all the paths and file extensions and it never finds anything besides arcade games.

I briefly considered it might be a permissions thing but I'm not sure that's even possible given that the games all live in a fat partition, which doesn't support Linux permissions (that I know of). Then again the MRAs that it _does_ find all live on that partition too so that seems pretty unlikely in general.

**Comment by mrchrisster** [comment]
I wonder if this is happening because of recent changes in the code... Can you try the test branch please? This is an older version that I personally verified working. To switch to test branch, you have to set branch=test in Sam's in file.

**Comment by 0x15e** [comment]
> I wonder if this is happening because of recent changes in the code... Can you try the test branch please? This is an older version that I personally verified working. To switch to test branch, you have to set branch=test in Sam's in file (very bottom of file). Just run the updater after to switch to test branch

I just tested and can confirm the test branch works properly.

**Comment by mrchrisster** [comment]
Ok thanks for testing, Murray - and sorry for not responding earlier, @wyrfxrssn .
I'll see where the error was introduced and update main branch accordingly

**Comment by mrchrisster** [comment]
Please update your files, it should be working now

**Comment by 0x15e** [comment]
@mrchrisster Thanks! I'll give it a shot tonight and report back (although I'm sure it's fine now).

**Comment by mrchrisster** [comment]
Hopefully it's working now for you. You don't need to use the test branch anymore, all the changes are merged to main. So simply updating Sam should do the trick

**Comment by wyrfxrssn** [comment]
Got it working no problem today - appreciate y'all for fixing the issue! I also edited the ini settings and those are functioning properly as well. Thanks a bunch for makin' this thing and keeping it working. <3 <3

**Comment by mrchrisster** [comment]
Great to hear, thanks for the feedback
