### ISSUE TITLE
Proper way to add new changes to MBC?

### ISSUE THREAD

**Issue by InquisitiveCoder** [mrchrisster/MiSTer_SAM#102]
I'm interested in adding limited zip support to MiSTer Batch Control so SAM doesn't have to extract the file in the case of single-ROM zip files. I noticed your fork of the MBC repo seems to have diverged significantly from pocomane's and all of the recent commits to main have added new versions of the executable rather than changing the code.

Am I correct in assuming I should open my pull request against pocomane's repo?

**Comment by mrchrisster** [comment]
Either way works for me

**Comment by mrchrisster** [comment]
Hey @InquisitiveCoder 
I just tested the main branch and it's not working anymore. Do you have an idea why? 
```
 Let Mortal Kombat begin!
 Removing other instances of MiSTer_SAM_MCP... Done!
 Stopping activity monitoring...kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
 Done!
 Starting MiSTer Super Attract Mode...
 Monitoring controller /dev/input/js0...
 Monitoring controller /dev/input/js1...
 Monitoring mouse activity...
xargs: printf: terminated by signal 13
 Done!
```

**Comment by mrchrisster** [comment]
There are a couple things not working unfortunately. My setup has mostly large zips for each system and `partun --list` does not seem to work:
```
 Let Mortal Kombat begin!
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1164:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 Starting now on the Nintendo Game Boy Advance: DK - King of Swing (Europe) (En,Fr,De,Es,It)
```

**Comment by mrchrisster** [comment]
Testing through the last revisions, my setup works properly with your [first whitelist commit](https://github.com/mrchrisster/MiSTer_SAM/commit/12cb35fae88f41efb2014e4804ff6106a16947e0)

I'll revert to this version now until we figure out what's wrong with the most recent revisions

**Comment by InquisitiveCoder** [comment]
Oof. Sorry for the trouble. I had tested this on my machine for a while before opening the pull request, so I thought everything was working fine. I wonder if this is a problem that only occurs with larger zips. Sorry for the trouble. Could you share...
- the number of files in the zip
- the size of the zip file
- your MiSTer_SAM.ini?

**Comment by InquisitiveCoder** [comment]
It turns out Rust's println! macro doesn't handle broken pipes very gracefully. I've opened a PR for partun with a fix (https://github.com/woelper/partun/pull/4).

I suspect the "kill: usage: kill" error is similar (if not the same) as the problem I addressed in https://github.com/mrchrisster/MiSTer_SAM/pull/99. I'd seen that error before and none of my whitelist/zip-handling PRs touched any calls to `ps` or `kill`, just the `next_core` function. I'll look into it soon. It's probably duplicated in several places.

**Comment by mrchrisster** [comment]
Sounds great! Please make sure you use the test branch when fixing the whitelist feature since it has all the mgl functionality implemented.

**Comment by mrchrisster** [comment]
Main branch is now merged with test branch

**Comment by mrchrisster** [comment]
I've seen people asking for the feature as well. By all means, please take a crack at it!

**Comment by mrchrisster** [comment]
Since MiSTer doesn't use MBC anymore, I'll close this issue for now.
