### ISSUE TITLE
MGL files and the future of SAM

### ISSUE THREAD

**Issue by InquisitiveCoder** [mrchrisster/MiSTer_SAM#103]
Sorgelig just added a feature that lets you launch an arbitrary game using a file that's similar to an MRA, except it's not arcade-specific. If SAM took advantage of this, it could simplify the game-launching code in to "pick a random MGL file from a folder and launch it." No need to worry about core-specific paths, file extensions, whitelists, blacklists, listing and extracting from zip files, or even using MBC. It'd also make the random selection better since every game would have the same probability of being chosen (as opposed to now, where each core has an equal probability games in a core with a shorter game list have a higher probability.)

Of course this assumes the user has spent the time to create the MGL files for their SAM game list, so it's not like we can just delete all the old functionality without breaking everyone's SAM setups. Would it be alright if I forked the project?

**Comment by mrchrisster** [comment]
Just saw your reply on pocomane's GH. First of all congrats on the new addition to your family and sorry I haven't had time to respond to your request yet.
Mgl looks exciting, I'll play around with it next week when I have some time.

**Comment by InquisitiveCoder** [comment]
No worries, we all have more important things to do than playing around with a MiSTer ;) If I find a bit of spare time I'm also going to experiment with MGL and see if I hit any problems using it in my MiSTer's SAM setup.

**Comment by mrchrisster** [comment]
MGL is now implemented
