### ISSUE TITLE
Issue using custom game subdirectories with spaces/special characters

### ISSUE THREAD

**Issue by rgdelato** [mrchrisster/MiSTer_SAM#106]
Hello there!

I'd like to set some custom game directories with paths that look like this: `/media/fat/games/Genesis/4 Game Series Collections/Best-Of Lists/V's Recommended Games - 4chan`. I've tried escaping the spaces and special characters a few different ways, but I haven't been able to get it to work.

I'm probably just doing something wrong, and if so, I'd be glad to make a PR updating the README!

**Comment by mrchrisster** [comment]
Thanks for reporting!
SAM had issues with spaces. It's fixed in the new mgl version which you can test by enabling test branch:
https://misterfpga.org/viewtopic.php?p=46096#p46096

**Comment by rgdelato** [comment]
The new test branch seems to work! I'm not really testing any of the difficult use cases (I've only really been shuffling through non-CD console games), but yeah, it's working great so far. I'll close out this ticket.

Thanks!
