### ISSUE TITLE
Fix Downloader database for MiSTer SAM script

### ISSUE THREAD

**Issue by theypsilon** [mrchrisster/MiSTer_SAM#111]
Every time the launcher for MiSTer SAM changes, these fields need to be updated:

<img width="706" alt="image" src="https://user-images.githubusercontent.com/852246/160294440-34140d5f-a534-4338-bc6b-330500059af7.png">

MD5 and Size fields always need to match the values from the script file, otherwise users will get errors. This is a measure to prevent against network errors.

Right now new users of Update All are getting errors when they activate this database. Thus this should be fixed asap.

I suggest having a GitHub Actions workflow that triggers on push, that would modify these fields automatically whenever there is a change in that script, that way maintenance will be 0.

Unfortunately, if errors are persisting over a longer period of time I'll have to remove this option from Update All to avoid confusion from new users.

**Comment by mrchrisster** [comment]
Hey, thanks for the pointer. I'll update it tonight or tomorrow and will look into GH actions, cheers

**Comment by theypsilon** [comment]
Thank you so much!

**Comment by mrchrisster** [comment]
I set up a GH action that seems to have done the trick, updating hash, size and timestamp every time `MiSTer_SAM_on.sh` is changed

**Comment by theypsilon** [comment]
Works like a charm, errors have disappeared, and the script looks good. Thanks for doing it so quick!

**Comment by mrchrisster** [comment]
Excellent, glad it's working!
