### ISSUE TITLE
Run MiSTer_Sam_on.sh arcade kills first xxd of tty2oled

### ISSUE THREAD

**Issue by venice1200** [mrchrisster/MiSTer_SAM#113]
Hi,
if I run "MiSTer_Sam_on.sh arcade", the first tty2oled Picture is not shown as some task kills the xxd task.
Up from the second Arcade it works fine.

![IMG_7833](https://user-images.githubusercontent.com/43762187/160296202-f33d9f73-74eb-467d-8963-4eb98b43ad05.jpg)

Cheers
Lars

**Comment by venice1200** [comment]
It looks to me is has to do with 
[MiSTer_SAM_MCP and the ](https://github.com/mrchrisster/MiSTer_SAM/blob/ebaf1ff2df3adb131d27d86a06ec8b56f4e081ed/.MiSTer_SAM/MiSTer_SAM_MCP#L79)

**Comment by venice1200** [comment]
We are trying to get a Version working which doesn't need so much changes within SAM.
But this is WIP.

**Comment by mrchrisster** [comment]
Xxd currently is used to detect keyboard input in SAM. We could use a python script instead like we do with joystick detection for example. I can take a look in a couple hours..

**Comment by venice1200** [comment]
Looks food to me!
MiSTer_SAM_on.sh arcade works fine without the start-picture problem.

**Comment by mrchrisster** [comment]
ok great :)

**Comment by venice1200** [comment]
Uuups, typo.
Mahlzeit 😄
