### ISSUE TITLE
Cannot turn off SAM

### ISSUE THREAD

**Issue by thehughhefner** [mrchrisster/MiSTer_SAM#116]
Hi,
It is not possible to turn off SAM even though I run the off script. 

To recreate (maybe start from scratch):
Only have MiSTer_SAM_on.sh in Scripts folder -> Execute it -> go back to mister main menu -> Execute MiSTer_SAM_off.sh -> You will see that it will not turn off.

**Comment by mrchrisster** [comment]
Thanks for your bug report! 
We switched to a new way of starting SAM. If you had executed Enable first, it would switch off as well. I updated SAM now to also detect the old startup method when turning it off.

**Comment by thehughhefner** [comment]
Hi,
This is still not working. The recreation steps are exactly the same as I showed in the first comment

**Comment by mrchrisster** [comment]
Can you update and try again? Thanks for testing!

**Comment by mrchrisster** [comment]
Please try with the most recent version. MiSTer_SAM_off.sh is actually just to disable auto start. Opening the menu and go to Stop SAM will stop the cycle.  I changed MiSTer_SAM_off.sh to now also stop the active cycle. Please update and report back.

**Comment by Paradox** [comment]
;;
				stop) # Stop SAM immediately
					there_can_be_only_one
					tty_exit
					echo -e "\0000\c" > /media/fat/config/Volume.dat # Reset Volume
					echo " Thanks for playing!"
add this ===>		echo "load_core /media/fat/menu.rbf" > /dev/MiSTer_cmd
					break
					;;
