### ISSUE TITLE
Only launch one core doesn't work

### ISSUE THREAD

**Issue by thehughhefner** [mrchrisster/MiSTer_SAM#117]
Selecting a core (for example Neo geo) in "Games from only one core" doesn't work. Even though I select neo geo, it launches another core.

**Comment by mrchrisster** [comment]
This works fine for me. Does Neogeo work with SAM when you only have one core in the corelist in MiSTer_SAM.ini ? 
(You can edit the ini through the menu if you want to give that a try)

**Comment by mrchrisster** [comment]
can you update and check if it works now?

**Comment by thehughhefner** [comment]
Hi,
This works now. Closing the ticket
