### ISSUE TITLE
SAM autostart prevents TTY2OLED normal functionality

### ISSUE THREAD

**Issue by sigismond0** [mrchrisster/MiSTer_SAM#118]
Currently discussed in the interrupt thread, but deserves its own issue report.

With the new TTY autocontrol update, SAM takes over the TTY2OLED display with "Welcome to Super Attract Mode" immediately on MiSTer powerup, and prevents TTY2OLED's normal functionality from working.  The only way to restore functionality is to issue a mister_sam_on.sh stop command (TTY will work until the next reboot or the next time SAM starts again) or mister_sam_on.sh disable (does not restore TTY functionality immediatly, but TTY will work starting at the next boot).

This means that as long as SAM autoboot is enabled, your TTY2OLED will only ever say "Welcome to Super Attract Mode", at all times unless SAM is actively shuffling cores.  

I think we've established a couple of options in the other thread:

1. Accept this as intended behavior with the new SAM full control mode.
2. Consider reverting away form full control to the older functionality (which has other bugs)

I'm also curious if we can't have a third option--does SAM actually need to kill TTY2OLED and put up it's splash text the second the script starts at system boot?  Or could that part of the code be delayed based on the autostart timeout in the ini file?  This seems like the best solution, as it would keep all the benefits of SAM full control, while also allowing TTY2OLED to work normally as long as SAM doesn't actually start shuffling.

**Comment by mrchrisster** [comment]
this should be fixed now

**Comment by Paradox** [comment]
Don't worry, a complete rewrite of the TTY2OLED support is under way.
