### ISSUE TITLE
Disable mouse movement detection?

### ISSUE THREAD

**Issue by dew0** [mrchrisster/MiSTer_SAM#12]
This is awesome, thanks for your efforts!
It would be great if you could turn off mouse movement detection only (via an ini setting?). I find it's too easy to accidentally move the mouse and drop out of the attract mode. Would still want to keep all the other methods of course :)

**Comment by Mellified** [comment]
Delete your INI, run the "on" script, and you should get the new version. We added support for per-type interruption of SAM.

**Comment by mrchrisster** [comment]
fixed
