### ISSUE TITLE
Nothing but Arcade will work with SAM

### ISSUE THREAD

**Issue by Paradox** [mrchrisster/MiSTer_SAM#122]
I want to start off by saying I did get (some of) them to work by switching to the test branch, but, the test branch is out of date with recent changes, and doesn't have gb gbc and s32x support, causing some other strange issues.

I'm currently reviewing the differences between the 2 scripts to see if I can work out what broke support for my romsets, and, also noticed that none of the cores that support chd are working, in either script.

I also can't get SAM to stop with any peripheral except the keyboard or mouse.

**Comment by Paradox** [comment]
It just completely skips searching for any roms after saying (Core) does not use zips!

I also think the problem with the rest of my roms is the new everdrive zip support, I don't use them, but, I do have multiple files in large zips (usually organized by region).

**Comment by Paradox** [comment]
I made the changes to allow changing the location of the rbf file for each core, and, now, PSX acts like the other CD Rom based systems, and just boots to the BIOS

**Comment by Paradox** [comment]
A new issue has arisen, skip doesn't change the rom, so, TGFX16-CD ends up trying to run a MegaCD or PSX disk when I use it... which also won't work, obviously.

**Comment by mrchrisster** [comment]
Most of your issues should be solved with the pending update. I might be able to push it out later today. It falls back to selecting the biggest Rom pack of you don't use Everdrive packs..

**Comment by Paradox** [comment]
I figured out most of my problems, I think... It looks like the mgl implementation has a bug if you have your game folders on a USB drive... ugh. no matter where the mgl points to.

**Comment by mrchrisster** [comment]
You need to set USB paths in the ini, then mgl works fine.

**Comment by Paradox** [comment]
set it where? I have 2 USB drives, by the way.

**Comment by Paradox** [comment]
well, I copied a megaCD chd to the SD card, changed the ini settings. turned off the MiSTer, unplugged both USB drives, and turned it back on, it found the chd file, but, I got exactly the same results. I'm about to give up on this.

**Comment by mrchrisster** [comment]
Never tested with 2 USB drives but i know of someone having all chds on usb and SAM picks those up after setting game paths

**Comment by Paradox** [comment]
/media/fat/Scripts/MiSTer_SAM_on.sh: line 1661: CORE_PATH_RBF: bad array subscript
/media/fat/Scripts/MiSTer_SAM_on.sh: line 1661: MGL_CORE: bad array subscript
/media/fat/Scripts/MiSTer_SAM_on.sh: line 1662: MGL_DELAY: bad array subscript
/media/fat/Scripts/MiSTer_SAM_on.sh: line 1662: MGL_TYPE: bad array subscript
/media/fat/Scripts/MiSTer_SAM_on.sh: line 1662: MGL_INDEX: bad array subscript
/media/fat/Scripts/MiSTer_SAM_on.sh: line 1643: CORE_PRETTY: bad array subscript
/media/fat/Scripts/MiSTer_SAM_on.sh: line 1643: CORE_LAUNCH: bad array subscript
/media/fat/Scripts/MiSTer_SAM_on.sh: line 1673: CORE_SKIP: bad array subscript

I also get this, about 50% of the time.

**Comment by Paradox** [comment]
> Never tested with 2 USB drives but i know of someone having all chds on usb and SAM picks those up after setting game paths

Yes, it picks them up, just fine, but, they don't run, it just goes to the BIOS.

**Comment by mrchrisster** [comment]
Open the menu and reset game lists.
That step will change in the new version, but if you would like to test SAM right now, you have to do this step in between path changes

**Comment by Paradox** [comment]
doesn't work with the USB drives in...

**Comment by Paradox** [comment]
I've been awake for far too long, working on this, work is going to suck.

**Comment by mrchrisster** [comment]
Get some rest man. As I said, this script will be updated shortly. I'll do some tests with multiple USB drives as well

**Comment by Paradox** [comment]
If you want to look through what I have changed, I forked, and committed a pull request to my own fork (So I can implement the changes better, later, feel free to look through, there are some other changes, such as things that weren't added, and, a lot of trailing whitespace removed... I hate trailing whitespace...

**Comment by Paradox** [comment]
OK, I committed all the changes I made to my fork. If you think a PR is necessary, let me know, otherwise, take what suits you.

**Comment by Paradox** [comment]
Just so you know, it is necessary to remove or rename any ROM folders you aren't using, for the mgl to work... I hope they fix that, but, it looks like it's working, now.... I had some folders left on the fat/games directory, because, everytime I update, it adds them back...

**Comment by Paradox** [comment]
Also, it still isn't recognizing controller input, and keeps starting up, even though I am scrolling the directories with one...

**Comment by mrchrisster** [comment]
just updated `MiSTer_SAM_on.sh` with all the recent code changes. Hope this works better for you.
I tested with two usb sticks and SAM plays games from both directories, not sure if this is working now because of the new code..
Controller input only works for buttons, not for DPAD. If you spend a lot of time in the menus without confirming or going back, just extend `samtimeout` var.

**Comment by Paradox** [comment]
> just updated `MiSTer_SAM_on.sh` with all the recent code changes. Hope this works better for you. I tested with two usb sticks and SAM plays games from both directories, not sure if this is working now because of the new code.. Controller input only works for buttons, not for DPAD. If you spend a lot of time in the menus without confirming or going back, just extend `samtimeout` var.

It doesn't seem to recognize any buttons on the controller, at all.

**Comment by mrchrisster** [comment]
Then your controller is probably not supported.. some Bluetooth controllers don't work. What kind of controller is it?

**Comment by Paradox** [comment]
I'm not 100% sure where you intended it to be, but, because of your haphazard indention practices, you seem to be missing a } somewhere...

**Comment by mrchrisster** [comment]
Please submit more precise feedback. Without knowing how your rom structure looks like, i have no idea what's happening.

**Comment by Paradox** [comment]
> Please submit more precise feedback. Without knowing how your rom structure looks like, i have no idea what's happening.

Genesis, for example has 3 zip files
-rwxr-xr-x 1 root root 656399640 Oct 26 00:54  _Check.zip  <---mostly .bin files that I need to check.
-rwxr-xr-x 1 root root 645055138 Oct 26 00:58  _Games.zip <---actual, verified .md files
-rwxr-xr-x 1 root root   7556794 Oct 26 00:50 '_Mini Pack.zip' <---All the games from the Genesis Mini (probably redundant)

because _Check.zip is the largest file, the script fails to find any roms for Genesis... because it doesn't process the other 2 zips.

**Comment by Paradox** [comment]
SNES
-rwxr-xr-x 1 root root    532479 Oct 26 08:25 BRAZIL.zip
-rwxr-xr-x 1 root root   6430210 Oct 26 08:25 DEMO.zip
-rwxr-xr-x 1 root root  46836286 Oct 26 08:25 EUROPE.zip
-rwxr-xr-x 1 root root  13604227 Oct 26 08:25 JAPAN.zip
-rwxr-xr-x 1 root root   5438551 Oct 26 08:25 TRANSLATED.zip
-rwxr-xr-x 1 root root 639289409 Oct 26 08:26 USA.zip
 While USA is the biggest, and would conveniently choose all English roms, I like the idea of it selecting from the other zips, sometimes, as well.

**Comment by Paradox** [comment]
If you don't want to create huge games lists, maybe you could have an option that limits the number of games added to the list from each zip, according to the size, or something.

**Comment by mrchrisster** [comment]
Ok thanks, that's helpful! There is a function that should process the next biggest zip if the first one does not have any valid roms inside, so I got to take a look at that.
In general Everdrive packs work the best with SAM but the more custom packs are supported, the better...

**Comment by Paradox** [comment]
Just so you know, I'm still not getting PSX or MegaCD  games loading properly, and, I'm fairly certain it's probably some sort of bug with the mgl implementation, because your script seems to be doing everything correct, and getting the mgl file made, proper, as far as I can tell, those cores just seem to be ignoring the games for some reason... Have you tested with MegaCD and PSX?

**Comment by mrchrisster** [comment]
Yes - and i know of a lot of SAM users that have MegaCD and PSX working. Only CHD file format is supported. Do you have BIOS set up and games launch when being selected directly?

**Comment by Paradox** [comment]
> Yes - and i know of a lot of SAM users that have MegaCD and PSX working. Only CHD file format is supported. Do you have BIOS set up and games launch when being selected directly?

Yes

Also, I just noticed the sounds don't always get unmuted when I move my mouse or press a keyboard key to exit.

**Comment by mrchrisster** [comment]
They should get unmuted but you won't see that right away since controls for unmute are not interactive. After a reboot, everything should be unmuted again.

For megacd, can you post a mgl? what bios are you using?

**Comment by Paradox** [comment]
<mistergamedescription>
<rbf>_Console/megacd</rbf>
<file delay=1 type=s index=0 path="../../../../media/usb1/games/MegaCD/chd/USA/Compton's Interactive Encyclopedia (USA) (Version 2.10) (RE2).chd"/>
</mistergamedescription>

As far as BIOS, I'm pretty sure it's the one that comes from the BIOS getter script.

**Comment by mrchrisster** [comment]
Looking good. Only thing I can think of is that maybe having a folder called "chd" might mess with mgl...

**Comment by Paradox** [comment]
TGFX16CD is setup the same way, and works fine.

**Comment by mrchrisster** [comment]
Strange.. Can you launch the mgl from OSD? Maybe renaming the folder is worth a try?

**Comment by Paradox** [comment]
after hundreds of attempts, for no reason at all, this one is actually loading

```
<rbf>_Console/megacd</rbf>
<file delay=1 type=s index=0 path="../../../../media/usb1/games/MegaCD/chd/USA/Super Strike Trilogy (USA) (Unl).chd"/>
</mistergamedescription>

```

but, umm... it seems to have loaded in GAMEBOY core (didn't actually run, of course) strange

**Comment by mrchrisster** [comment]
The mgl looks correct so this might be a non SAM related issue with mgl... 
I have one other idea... which file system is usb1? It might be an issue with capitalizing. It doesn't matter for exfat but does matter for linux file systems.

**Comment by Paradox** [comment]
ext4
I downloaded a batch file for making mgl files, from the forum, earlier, and, I put one of them in a test directory on the main mister menu (alongside console, etc.) and tried to run them both, yours failed, and this one worked

```
<mistergamedescription>
 <rbf>_console/MegaCD</rbf>
 <file delay="1" type="S" index="0" path="chd/USA/3 Ninjas Kick Back (USA).chd"/>
</mistergamedescription>

```

I think you might be right about capitalization, I'll edit the mgl and see if it runs, if so... you'll need to upload a new version of the script that uses the correct case.

**Comment by mrchrisster** [comment]
Capitalization is something that isn't consistent in the script but the correct case would be determined by megacdpath in the ini. You can set it there.

**Comment by Paradox** [comment]
```
<mistergamedescription>
<rbf>_Console/MegaCD</rbf>
<file delay=1 type=s index=0 path="chd/USA/Super Strike Trilogy (USA) (Unl).chd"/>
</mistergamedescription>

```
This worked, the one with ../../../ didn't still makes me wonder why TGFX16-CD works, though.

**Comment by Paradox** [comment]
I always use proper casing, it's your script that is using megacd instead of MegaCD

**Comment by mrchrisster** [comment]
The console folder is mounted on SD which is exfat so casing doesn't matter here. Did you get it working?

**Comment by mrchrisster** [comment]
Agreed, better error and case handling would be nice! 
 Since SAM is written with update_all and Everdrive packs in mind, I don't see a reason for supporting it at this point though.

**Comment by Paradox** [comment]
another suggestion would be to make the process of finding the paths more automated, like the BIOS getter script (and, now the mame and hbmame getter scripts, thanks to my suggestion and contribution through a PR, to their maintainer) because, since I use 2 USB drives, MiSTer will often set one as usb0 and the other as usb1, and, the next time it boots, it might switch them around...

**Comment by Paradox** [comment]
ok, I hacked the mgl creation process to remove the path to the actual games directory, which fixed PSX and MegaCD, but, broke TGFX16-CD, because it seems to expect the cd images to be in the normal TGFX16 directory, so, now it's the opposite...

**Comment by mrchrisster** [comment]
That's exactly the reason why SAM is working that way... because I couldn't get TGFX16CD working otherwise

**Comment by Paradox** [comment]
https://github.com/MiSTer-devel/Main_MiSTer/issues/588

**Comment by Paradox** [comment]
You should go back to the default behaviour, and allow the MiSTer devs to fix the issue on their end.

**Comment by mrchrisster** [comment]
Why is that? This would break TGFX16CD for everyone. This won't be changed until it has been addressed. As I said, MegaCD work well for most users, so does PSX

**Comment by Paradox** [comment]
Now that I know more about how MGL works, except for the situation with TGFX16-CD as long as you are using the standard Rom directories, you don't need to define anything, even if your roms are on USB, since the MiSTer framework already takes care of telling the cores where to find the roms. all you would need is the names of subdirectories, such as chd or USA or, whatever, for those who want a particular subdirectory, or, even zipfile, to be used.

**Comment by mrchrisster** [comment]
Symbolic links work on exfat with Mister, yes. Sorg is recommending against using them since it's a very hacky feature and can be unreliable. 

One of the reasons we have custom paths in SAM is if you want to play a custom selection of roms, you can point to that folder. Or what if you have some roms for a core on SD and some externally? I found the automatic folder selection process to not always pick my desired folder. When first implementing MGL, we wanted to support the way it's meant to work, but a lot of users ran into issues, that's why we ended up with the current MGL implementation.

The main issue i see here is that your USB drives swap location on reboot which you might be able to fix through defining by UUID in fstab.
The reason MegaCD and PSX are not working has to be an issue with capitalization with `/media/usb1/games/MegaCD`.  You can also try an extra `../` in the beginning. 

I'm glad you found a solution that works for you. As one of the authors behind SAM i have to carefully choose which setup provides the least amount of problems for most SAM users and right now, these issues you are having are pretty specific to your setup.

**Comment by Paradox** [comment]
Yeah, well, I have found many issues with the script all around, and I think I'll just rewrite just about everything, and keep my branch available for anyone else who desires it to work the way that works for me.

**Comment by mrchrisster** [comment]
Great, please do. Always great to get inspired by other people's work - and that goes both ways.

**Comment by Paradox** [comment]
By the way, SMS and GG have a similar problem, as does GB and GBC, but, I have figured out how to fix all of those, without ../../../

**Comment by mrchrisster** [comment]
Ah, you got me excited there. I'll be looking again at MGL once TGFX16CD is fixed. Auto folder selection would be nice for sure!

**Comment by Paradox** [comment]
Well, it wasn't easy, and, it probably looks like a terrible hack job, but, I have it using default directories, no matter what device, or devices, they are on. so, you can store all of your regular roms on your SD Card, and all of your CHD images on a separate USB or, more than one USB, the only real caveat, is the same one MiSTer has, by default, make sure the directory you want to use, doesn't have an empty version of itself, on a higher priority device, /media/games/fat is the lowest priority, and, usb0 (for some strange reason) is the highest priority I say some strange reason, because, I believe it should be usb5, but, oh well.

**Comment by Paradox** [comment]
After I commit this, I'm going to start working on getting full lists of all roms for each core, no matter how many zips or loose roms there are, and, make it gracefully ignore any unrecognized files, instead of failing... My genesis still wouldn't work, even after I removed that other zip full of bin files, turns out, there were 3 bin files (which the core does support, by the way) and, it kept failing the other several hundred md files in the zip, because it didn't recognize those 3 files...

**Comment by Paradox** [comment]
There are also some weird race conditions that cause it to try to load another rom, directly after loading one, before the timer runs out, and, it ends up trying to run chd files in cores that don't support them, or, for instance, snes roms on the gba core...

**Comment by mrchrisster** [comment]
Nice man. I started working on just copying all roms and zips in a path to the game list, which will replace all the romcompare and zip logic. Partun just got updated to allow me to easily write a zip to a list for mgl to use.
One thing I'm looking for help with is stripping duplicates from the list. Everdrive often has the same rom in multiple directories and it would be neat for SAM to filter all duplicates...

**Comment by Paradox** [comment]
Do they actually duplicate the roms, or, use symlinks?

**Comment by Paradox** [comment]
Most recent changes, committed.

**Comment by Paradox** [comment]
> Nice man. I started working on just copying all roms and zips in a path to the game list, which will replace all the romcompare and zip logic. Partun just got updated to allow me to easily write a zip to a list for mgl to use. One thing I'm looking for help with is stripping duplicates from the list. Everdrive often has the same rom in multiple directories and it would be neat for SAM to filter all duplicates...

That will likely be the easy part...

**Comment by Paradox** [comment]
Man, I wish sorg would just go ahead an add CHD, I don't feel like forking the main repo, just for a less than one line PR...

**Comment by Paradox** [comment]
Sorg and birdybro both say the TGFX26-CD thing is fixed, but, it still isn't working on my MiSTer, not sure why. Can you test?

**Comment by mrchrisster** [comment]
I can test on Tuesday

**Comment by Paradox** [comment]
I'm not at home I'm at work so I can't test right now but apparently I was testing with the latest release but the change hasn't been put into the latest release yet it's in unstable nightlies.

**Comment by mrchrisster** [comment]
Great, thanks for letting me know

**Comment by Paradox** [comment]
Yeah, I have now tested, and, it definitely works, if you use unstable.

**Comment by mrchrisster** [comment]
Great news, glad this is fixed. Having an auto path selection option will be great for SAM. Do you mind creating a PR? we could create an option in the ini (like autopath="Yes") and leave it default off for now until it becomes part of the main branch...

**Comment by mrchrisster** [comment]
I'll also commit the changes to rom detection once I'm near my Mister again. It basically creates a list of all files (zipped or unzipped) in a folder, strips duplicates , sorts it and filters by extension. This should help adding all your roms from the different zips to SAM's shuffle.
All the work is done, just need to test it.

**Comment by Paradox** [comment]
I'll work on it, when I get home

**Comment by mrchrisster** [comment]
Take a look at `MiSTer_SAM_on.sh` in the test branch. It has all the new game selection logic implemented.

**Comment by Paradox** [comment]
Yeah, I had already pulled the new partun and made changes to support it.

**Comment by Paradox** [comment]
Looks like I have some work to do, to bring mine back in line, so I can use the new changes, and continue to be able to submit other PRs...

**Comment by Paradox** [comment]
I see this change very much simplified the entire process, and you don't have to specifically support everdrive packs, separately, anymore. Although, I could see that being added as an option, to only recognize everdrive packs.

**Comment by mrchrisster** [comment]
Yes, it's very much simplified now so I don't think Everdrive needs to be supported separately anymore. Hopefully it works well for everyone.
Supporting only certain roms is the next step for sure. Everdrive packs are organized by language, hacks, translations etc. in separate folders.
I'm working on a game list editor to select things like "only show japanese roms" or "exclude hacks"

**Comment by mrchrisster** [comment]
Thanks for the PR, I'll test later today.

**Comment by Paradox** [comment]
> Thanks for the PR, I'll test later today.

I hope it works okay I had to refactor a bit to fit with your stuff and I'm sure it still works but I haven't actually tested it in the exact form that I pushed it in

**Comment by mrchrisster** [comment]
I commited your PR and everything seems to be working fine. 
I did notice though that for S32X it keeps using the genesis path. Shouldn't it use the S32x path?

**Comment by Paradox** [comment]
That's a mistake you made, that I fixed in my fork, but, didn't include with the PR, because it's unrelated.

**Comment by mrchrisster** [comment]
Ok sounds good. Is it an easy fix you think?

**Comment by Paradox** [comment]
I just got home, a little while ago, and started testing, I definitely messed something up, I'm working on the fix now.

**Comment by Paradox** [comment]
I'll create the new PR, I got it working.

**Comment by Paradox** [comment]
I have another PR up that kind of goes hand in hand with the other commit, and allows extra directories under the default directory to work, again. Also removes the ../../../ from mgl creation.

**Comment by Paradox** [comment]
And, with your changes for gamelist creation, I have seen it use more than just one zip file to pull games from, so much better. The only suggestion I have for that is allowing it to make the list from subdirectories of the chosen directory. (possibly an optional setting)

**Comment by mrchrisster** [comment]
Thanks! I'll check the new PR later today and will put your name in the Thanks section at the beginning of `MiSTer_SAM_on.sh`

**Comment by Paradox** [comment]
I'm going to suggest creating a dev branch, and implementing a release system, so main is always stable and tested, so users aren't subjected to being beta testers, unaware...

**Comment by mrchrisster** [comment]
Yes, we have a test branch for this. it can be activated by using `branch=test` in MiSTer_SAM.ini
We used to push everything to test but then got lazy at some point. It's a good idea to switch back to test for this
