### ISSUE TITLE
Joystick detection handling and improvement

### ISSUE THREAD

**Issue by mrchrisster** [mrchrisster/MiSTer_SAM#131]
Some modern Bluetooth controllers create additional input devices which break functionality with SAM since they appear to SAM as devices that constantly push buttons. This thread is trying to improve on the input button detection. 

SAM recognizes button pushes through monitoring the binary stream of js input devices.
Here is a script to test your input devices.

1. SSH into the mister and type `ls /dev/input`
2. Make a note of all js devices
3. Create a file with `nano joytest.py`
4. Paste the following content:
```
#!/usr/bin/env python

import struct
import time
import glob
import sys

packstring = "iiiiiiiiiiiiiiiiiiii"

infile_path = sys.argv[1]
EVENT_SIZE = struct.calcsize(packstring)
while True:
    try:
        file = open(infile_path, "rb")
        event = file.read(EVENT_SIZE)
        (a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t) = struct.unpack(packstring, event)

        if b != 8454144 or d != 25231360 or f != 42008576 or h != 58785792 or n != 109117440 or p != 125894656 or r != 142671872 or t != 159449088:
           print("Button pushed")
        time.sleep(0.2)
    except FileNotFoundError:
        print("Joystick disconnected")
        sys.exit(1)
```
5. Launch `./joytest.py /dev/input/js0` and see if buttons are detected. Repeat with all other js devices

**Comment by Paradox** [comment]
check out  evdev-joystick --l

**Comment by mrchrisster** [comment]
Nice, that's a good idea! I'll be back at my Mister setup on Friday and can take a look then

**Comment by mrchrisster** [comment]
Just updated joystick detection. @Paradox, do you have time to test?

**Comment by Paradox** [comment]
I'll check, now, but, I don't have a ps5 controller, so, someone else will need to confirm that part.

**Comment by Paradox** [comment]
At first, it wasn't working, but, I killed all the processes related to SAM and started it again, and, now, all of my controllers work.

I'm not sure if there is an issue with stop not killing all related processes, or, just an issue with my setup, since I have been doing a lot of testing, I have to run pick up my girls from school, so, I'll look into it more, later.

**Comment by mrchrisster** [comment]
It might have just needed a reboot. Great to hear your controllers are all detected now. Does button detection work on all of them?

**Comment by Paradox** [comment]
The start or select button doesn't seem to work on some controllers, and the dpad doesn't trigger on any that I have noticed, but, that may be correct behavior, I think you mentioned that to me, once before.

**Comment by Paradox** [comment]
Also, anytime I use stop, I get this message:
./media/fat/Scripts/MiSTer_SAM_on.sh: line 1686: kill: (1083) - No such process

**Comment by Paradox** [comment]
but, it does stop all SAM processes, might have just needed a reboot, like you said.

**Comment by mrchrisster** [comment]
> The start or select button doesn't seem to work on some controllers, and the dpad doesn't trigger on any that I have noticed, but, that may be correct behavior, I think you mentioned that to me, once before.
> 
> Edit: I notice some buttons just don't trigger it, maybe a controller mapping issue?

Yeah, the problem is that we receive raw input and when buttons are unmapped, it's kind of unpredictable how the joystick will operate. Through extensive testing we determined that for all devices we checked, the four main buttons are identical for all controllers. While Start/Select worked on my controller, it gave other users trouble with SAM stopping without buttons being pushed. I never figured out how to read the dpad unfortunately...

**Comment by Paradox** [comment]
Somewhere, in these last commits, you broke stop, it doesn't stop the currently playing game, when using playcurrentgame="No"

**Comment by Paradox** [comment]
I'll clean it up, and add a disable variable, and you can test it, too.

**Comment by mrchrisster** [comment]
Joystick handling and keyboard change detection have been implemented
