### ISSUE TITLE
(Feature Request) playcurrentgame advanced feature

### ISSUE THREAD

**Issue by BHuqueriza** [mrchrisster/MiSTer_SAM#150]
Hello, I'm suggesting a modification to the "playcurrentgame" feature:
1. When set to "yes", player must hit the Start button (default) to relaunch the current game with sound. Pressing any other button will reboot SAM to the main menu
2. Allowing an option to rebind the Start button to any user-specified button

**Comment by mrchrisster** [comment]
Thanks for your feedback. 
Unfortunately we don't have control over the different button states with SAM. We can tell that a button has been pushed but we don't know which button that is on the controller.

Hopefully one day button input will be easily read in linux on the MiSTer platform.

**Comment by mrchrisster** [comment]
We now have start button detection to play current game. Just Set up your controller (one at a time) under SAM Menu -> Settings -> Setup controller
