### ISSUE TITLE
Fails To Run

### ISSUE THREAD

**Issue by codingncaffeine** [mrchrisster/MiSTer_SAM#179]
I downloaded the file mister_sam_on.sh and put it in the /media/fast/scripts folder as suggested in the install instructions.  However when I try to run it from the mister I'm getting the error message:

"line 8: syntax error near unexpected token 'newline'

My only option is to press any key to continue which kicks me back to the main menu.

I tried re-downloading the script but it still fails.

mister ver 220529   OS v220413

**Comment by mrchrisster** [comment]
Thanks for letting us know. I'll try and replicate your problem and get back to you

**Comment by mrchrisster** [comment]
Can you enable MiSTer SAM in update all under misc, run update all and then run `update_MiSTer_SAM.sh` ?
This way we make sure the problems are not with downloading the script itself.

**Comment by codingncaffeine** [comment]
> Can you enable MiSTer SAM in update all under misc, run update all and then run `update_MiSTer_SAM.sh` ? This way we make sure the problems are not with downloading the script itself.

It's working fine with this method, no errors no issues.

**Comment by Paradox** [comment]
Sounds like the line endings were changed, when you downloaded it, or, when you transferred it to the SD card.
