### ISSUE TITLE
Global game list

### ISSUE THREAD

**Issue by theypsilon** [mrchrisster/MiSTer_SAM#19]
I'm a big fan of this tool, congrats for the work!

I just wanted to suggest an addition. It would be very nice if you could load a .txt file with a list of games to filter out all the junk the one could have in their SD. I see that there is a way to do it for MRAs, but not globally. Additionally, it would be interesting to have a couple of options when using that list like shuffle / sequential, or even a way to change the timeout per game basis.

**Comment by mrchrisster** [comment]
Thanks for your feedback! We've started working on a general exclusion list already. And we will have some games disabled by default that we know are causing issues. Should be coming in the next few days.

**Comment by theypsilon** [comment]
Very exciting, thanks!
