### ISSUE TITLE
Unable to detect DARKSOFT-Based NeoGeo (e.g. 'NEOGEO') folders/files

### ISSUE THREAD

**Issue by fignutz** [mrchrisster/MiSTer_SAM#191]
**Issue**
Once installed, the script is unable to detect/work with non-extension (_i.e. '.neo'_) NeoGeo games like DARKSOFT-based romsets (_i.e. fpga,m1rom,prom,etc._).

**Reproduce**
1. Install the script set manually or via the 'Update_all' script after setting the MISC setting to true for SAM files
2. Follow remaining initial setup instructions provided at this github repo
3. Modify the Update, On and INI shell scripts to point to 'NEOGEO' instead of 'NeoGeo' for the '.../games' directory
4. Run the 'update/create lists' option in the MiSTer_SAM menu, and watch how the number of detected Neo Geo games is always '0'

**Attempted Workaround(s) That Did Not Work**
- Adding all variations of loose rom file names that exist in a given named 'ENGLISH' Neo Geo folder (aligns with SAM settings/configs)
- Verifying the unzipped/folder names of ENGLISH named Neo Geo games match the names provided in the SAM scripts.

**Comment by Paradox** [comment]
Yeah you have to convert them to neo files mgl does not support it we don't support it

**Comment by Paradox** [comment]
There's a couple of good converters out there the one I used is on GitHub I can't give you a link right now cuz I'm on my phone I'm working

**Comment by Paradox** [comment]
It actually seems I used this one https://gitlab.com/loic.petit/darksoft-to-neosd

**Comment by mrchrisster** [comment]
We only support .neo. A little hint, google "htgdb gamepacks"
