### ISSUE TITLE
"No RBF Found" Message when input is detected

### ISSUE THREAD

**Issue by garrettkapp** [mrchrisster/MiSTer_SAM#194]
Hi Devs,

I updated MiSTer SAM recently, and started briefly seeing a "No RBF Found" message after interrupting the attract mode with an input. I've completely re-installed MiSTer SAM and started with a fresh copy of the ini file and am seeing the same behavior.
I've got a pretty standard set up, loading everything from the SD card. Nothing unique to my set up that I can think of that would impact this.

Here are the non-default settings I'm using (everything else is untouched):
```
gametimer=300
corelist="arcade"
mute="No"
playcurrentgame="Yes"
listenkeyboard="No"
```

I've noticed in the MiSTer_SAM_on.sh file, in the `sam_exit()` function, there is the following code:
```
	elif [ ${1} -eq 3 ]; then # Play Current Game
		sleep 1
		echo "load_core /tmp/SAM_game.mgl" >/dev/MiSTer_cmd
	fi
```

When I comment out the `echo` line, things seem to work normally with no error. Not sure if this has any other impacts, but at least as far as I understand, it will attempt to load the core that is already loaded and playing, so I wonder if this is necessary.

Cheers!

**Comment by mrchrisster** [comment]
Thanks for your detailed report. I just pushed this code in the most recent commit. I'll take a look next week to check why mgl reloading is misbehaving.
You can disable the error for now by setting playcurentgame=no for now

**Comment by mrchrisster** [comment]
Hey garrett,

can you please update and check if this is working now?

**Comment by garrettkapp** [comment]
Thanks for the quick fix! Everything seems to be working great now :D
I'll close this issue. Cheers!
