### ISSUE TITLE
Game audio level very faint/broken

### ISSUE THREAD

**Issue by PapiFed** [mrchrisster/MiSTer_SAM#195]
When running SAM after the latest update sound is missing or bearly audible.
Launching the same game manually from the Core does not present any audio issues.

**Comment by mrchrisster** [comment]
Just noticed the default was set to Core, so I assume that is the issue. I've changed the default setting back to `mute="No"`

**Comment by PapiFed** [comment]
Thanks for the quick troubleshooting !
