### ISSUE TITLE
tty2oled in named-pipes

### ISSUE THREAD

**Issue by venice1200** [mrchrisster/MiSTer_SAM#197]
Hi,
I had to add
```
declare -gl ttypicture="/media/fat/tty2oled/pics"
declare -gl ttypicture_pri="/media/fat/tty2oled/pics_pri"
```

to https://raw.githubusercontent.com/mrchrisster/MiSTer_SAM/named-pipes/.MiSTer_SAM/MiSTer_SAM_tty2oled 
to get the Core-Pictures shown again.

Without these lines you get only the text-version.

The scrolling is cool!
CU

**Comment by Paradox** [comment]
I have been seeing the pictures, but, I'll add it, anyway, next time I commit. Thanks.

**Comment by Paradox** [comment]
Although, it doesn't need -gl only -g
It works, in this case, because the entire URL is lowercase, already...

**Comment by venice1200** [comment]
> I have been seeing the pictures, but, I'll add it, anyway, next time I commit. Thanks.

Mmm, strange as I don't see the variable get a value.

**Comment by venice1200** [comment]
I updated my Named Pipe to Super_Attract_Mode.

To prevent garbage screens like this

![image](https://user-images.githubusercontent.com/43762187/180052739-626fe5d1-51ee-4410-9ebb-70510a33c9b7.jpeg)

add a tty_wait after each CMDDUPD.

**Comment by Paradox** [comment]
The only problem I have with using ttywaitfor is that that timer has to update every second not every second and a half

**Comment by venice1200** [comment]
I know.
But i get the weird pictures nearly on each start of an new game.

![image](https://user-images.githubusercontent.com/43762187/180066839-c72678f4-1cf7-40f6-b7ec-bf9f586dc74e.jpeg)

**Comment by venice1200** [comment]
I don't measure any big difference using the tty_waitfor after CMDDUPD.

**Comment by Paradox** [comment]
Yes, we have been noticing this for a very long time, it used to happen with CMDCLS almost every time we used it, the device is displaying the CMDTXT at the default center of the screen, instead of processing the command, properly, whatever the reason is.

**Comment by venice1200** [comment]
The issue is timing.
If you send commands one after the other it is possible that one of the CMD parameter himself is not correctly detected and the rest of the transmission is just seen as a plain corename which is then centered in the middle of the screen.

Thats an indicator of a timing-issue.

Using commands with output need a longer waiting time as commands which don't write anything to the display.

And tty2oled systems with 8266 are muuuch slower.

Waiting long enough or using tty_waitfor helps.

Reading from the Display is another problem as the different usb-serial chips behave different.

**Comment by Paradox** [comment]
We implemented a splashscreen for SAM, I use sleep 0.08 before it, and everything works fine, I replace that with tty_waitfor and get a data transfer error.

**Comment by venice1200** [comment]
Show me the Splashscreen Code and I can take a look.

There is no need for tty_waitfor but it gives you more control.

**Comment by mrchrisster** [comment]
Hey venice, if you update named-pipes it should now show the splash

**Comment by Paradox** [comment]
Yeah I figured out the issue and I looked further into it and you're right it wouldn't make much of a difference in time

**Comment by Paradox** [comment]
As far as the corrupted text that you're speaking of I personally have not seen it happen except when I was doing some testing and it was obvious it was my fault but please check out the latest version and let me know if it's still happens

**Comment by venice1200** [comment]
Got it!
Move the tty_waitfor in line 
https://github.com/mrchrisster/MiSTer_SAM/blob/fdef9c471561162af3e134f13e195ddc83576103/.SuperAttract/SuperAttract_tty2oled#L274
after the tail
https://github.com/mrchrisster/MiSTer_SAM/blob/fdef9c471561162af3e134f13e195ddc83576103/.SuperAttract/SuperAttract_tty2oled#L275

You can add another tty_wait after
https://github.com/mrchrisster/MiSTer_SAM/blob/fdef9c471561162af3e134f13e195ddc83576103/.SuperAttract/SuperAttract_tty2oled#L277

**Comment by Paradox** [comment]
I fixed it by removing the CMDCLST that was unneeded, because it does it's own random transitions, and have already put multiple tty_waitfor lines in, I'll take a look, later, and see if I caught the ones you mention, specifically.

**Comment by Paradox** [comment]
I'll leave this discussion open, incase anyone notices this is still an issue, and wants to comment.

**Comment by Paradox** [comment]
> @Paradox which tty2oled device are you using. Which MCU does it use?
> 
> I get the Splashscreen now, looks nice.
> But now I don't get the Core Logos shown.
> 
> https://user-images.githubusercontent.com/43762187/180384055-4a6b2837-10d1-4cea-b527-3eddd835c934.MOV
> 
> If you like I can add the Splashscreen to the Picture Repository.
> 

@mrchrisster would be the one to decide if it's ok to add it to the repo, but, I'm sure he wouldn't have a problem with it. we also want to add pics for the cores that don't have them, because they don't have their own, separate core, such as Atari 2600 game gear sg1000 gameboy, etc.

**Comment by venice1200** [comment]
Most of the consoles should habe their own icon.
Cores which supports more than one system, like the sms core, are a bit difficult to handle in case of a dedicated picture.

But if a picture exists, like for the atari2600, and you know the name of the picture, you can load it instead of the corename logo.

Double check out our google list:
https://docs.google.com/spreadsheets/d/1GR_8nBq3vY_SGQZ5pxLnU1XFWek1uq8uxNAnj0a4RCU/htmlview

**Comment by venice1200** [comment]
As the tty code is now part of main i will close this issue.
Many Thx
