### ISSUE TITLE
Using .cache folder

### ISSUE THREAD

**Issue by theypsilon** [mrchrisster/MiSTer_SAM#20]
I would like to propose using `/media/fat/Scripts/.cache/MiSTer_SAM` instead of `/media/fat/Scripts/.MiSTer_SAM`

The reason would be mainly that this way we reduce the amount of hidden folders in the Scripts folders for the users. Not a big deal, but having so many of these folders in the **Scripts** folder could be considered confusing and/or undesirable for some people.

**Comment by mrchrisster** [comment]
Thanks for the suggestion, makes sense! Keeping things tidy is a good thing. We'll consider changing over to `.cache` folder but don't have immediate plans to do so. Mostly because we already did a folder change once (from `/media/fat/MiSTer_SAM`) and it wasn't as seamless a transition as we had hoped

**Comment by Mellified** [comment]
After reviewing this, I don't think it makes sense to use .cache. We're storing actual operating code in the `.MiSTer_SAM` directory. While we update this each time `MiSTer_SAM_on.sh` is run the files downloaded can be permanent for offline installations. 

We don't want it to be a visible directory for fear users will forget what SAM stands for and delete the files accidentally.

**Comment by theypsilon** [comment]
The .cache directory wouldn't be visible either.

**Comment by Mellified** [comment]
We moved from `/media/fat/MiSTer_SAM/` to `/media/fat/Scripts/.MiSTer_SAM/` to hide the folder from accidental deletion. Moving to `.cache` doesn’t offer us any benefit, and it implies the data is transient when it is not. 

A cache makes sense for a tool that is expected to have online functionality. Losing the cache is just inefficient. 

MiSTer_SAM has no inherent online requirement. Losing the files in `.MiSTer_SAM` would be catastrophic for the functionality of the script in an offline environment. So those files are not a cache and don’t belong in that folder.

**Comment by theypsilon** [comment]
Right semantics (even though I doubt anybody would apply them to their Scripts folder on mister), but that wasn't the point. I know people have complained about littering their Script folder with too much stuff, because they later open the FTP client for deleting a last_run* file and the clutter is right there, but of course I don't want to insist on it.

**Comment by mrchrisster** [comment]
Appreciate your feedback and we actually opened a new ticket with the aim of reducing clutter. I wish there was a folder for custom scripts we could be using. For the time being a dedicated hidden folder seems like the best option for us. If you have other suggestions besides the cache folder where to store our data we're happy to hear your ideas.
