### ISSUE TITLE
SAM fails to detect controller during ini_settings.sh

### ISSUE THREAD

**Issue by musso-joseph** [mrchrisster/MiSTer_SAM#205]
I booted the ini_settings script from the Scripts menu from the MiSTer main menu, however when trying to change the MiSTer font SAM kicked in. It seems like SAM doesn't detect controller input while in the ini_settings GUI. I don't know if this is also the case for other scripts, as I haven't tried to reproduce with them yet.

**Comment by mrchrisster** [comment]
That's good to know. SAM should have detected your keyboard. Can you post output of `ps aux | grep py` ?

**Comment by mrchrisster** [comment]
The issue might be that SAM unfortunately can't detect dpad pushes, only button pushes. So maybe you were just browsing with the dpad for a minute? (That's the default gametimer before Sam starts)

**Comment by musso-joseph** [comment]
That's definitely it - I was only moving the d-pad up and down while trying to pick a font.
