### ISSUE TITLE
Feature Request: Block All, Use Allowlist

### ISSUE THREAD

**Issue by musso-joseph** [mrchrisster/MiSTer_SAM#207]
SAM would be more useful to me if I could explicitly DENY ALL games, and use only an ALLOW LIST curated by me. Maybe an INI setting that enables the use of a user-managed folder with MGL files? I have no problem defining the MGL files myself. 

The current method of adding games to a DENY/BLOCK LIST is less useful when I have hundreds of games on my NAS, but am only interested in using the attract mode of a few.

Better yet, maybe through regex support or something similar, you could add support for community curated "playlists" which are text files using the common titles of games? Regular expression support is useful here as games/ROMs/etc may have slightly different names.

**Comment by Paradox** [comment]
I might consider this, but, I think really all you need to do is turn off the create_all_gamelists, and make the gamelists, yourself, containing only the games you want, or, just move all the games you want into a subdirectory, and set your (core)extrapath= to that directory (allowed_games for example) and delete your existing gamelists, and let it regenerate, and it will only add the files in that folder, as long as you aren't using samindex, as it doesn't GAF what you want, it only uses default paths.... grrr

**Comment by Paradox** [comment]
I don't really do much with the main branch, I spend almost all of my time getting the named-pipes branch ready to become main, so, i wasn't aware of all the changes @mrchrisster has done, there, and, it looks like he either has implemented, or, plans on implementing a whitelist for the main branch, but, I cannot say whether it works, or, not, and, it also looks like he nuked the defaultpath option, and made samindex the only way to create gamelists, so... and, it also seems there are issues with it, over all, so, I would recommend using the main-rollback branch, if you want to go back to when the script was more stable, and wait for him to work it out, or, you can try out the named-pipes branch and, the options I mentioned in my last post, should definitely work, and, if you find something that isn't working, just report it on the issue tracker, and, i would suggest, anyone reporting an issue, be sure to indicate what branch you are using, so we know how to help.

**Comment by mrchrisster** [comment]
Hey joseph,

we will be switching to named-pipes branch eventually but for now there is a pathfilter option that I just added. Please check if it works.

Just put any file path in the path filter section of MiSTer_SAM.ini.
For full control, you can edit SAM's gamelists directly by opening the file `/media/fat/Scripts/.MiSTer_SAM/SAM_Gamelists`

**Comment by mrchrisster** [comment]
use pathfilter or exclude list
