### ISSUE TITLE
Broke the script so it doesnt auto start and wont change games if using the NOW script

### ISSUE THREAD

**Issue by daemon5k** [mrchrisster/MiSTer_SAM#21]
Hello,

I love this script so its a bummer that I somehow broke it yesterday. I had it running for almost 24 hours and then something happened during an update and now it wont auto start regardless of the time set in the .ini. 

-For some reason if I delete the .ini and run the update to recreate it, it's set to a default of 60 instead of 300. Changing the settings of time to start or switch games seems to have no effect after being saved. After running the On script and sitting on the main menu nothing will happen.

-Running the NOW script works until its time for it to switch games. It just will remain on whatever the initial game that was selected.

-Running the update Script seems to run fine (Downloading MiSTer SAM on, Turning MiSTer SAM on, etc) however when its completing for some reason it shows the following text order:

"Removing other running instances of S93mistersam
Starting MiSTer Super Attract Mode...
DONE
Press ENTER to contine
Setting up watches.
Watches established."

Not sure why the Press Enter is out of order when it wasnt that way previously. It seems to do this every time now.

I tried running the default process but didnt see any sort of confirmation of the .ini being reset after entered the text listed.

Hope all this info helps as Id love to get it working again. Its seriously my fav MiSTer function! Appreciate all your hard work. 

also somehow managed to delete the entire script folder trying to return to default settings :( I grabbed the update all script and recreated the folder. ran update all and now it cant find the arcade cores and things are messed up :(

**Comment by mrchrisster** [comment]
Hey, thanks for your feedback. We added a lot of new  features to SAM in the last couple days. Deleting the ini and running `MiSTer_SAM_on.sh` should get everything working. The default setting is for SAM to only start now when you are in the main menu.  
  
After running the update, please do a cold reboot and let it sit in the main menu to see if it comes on.

**Comment by daemon5k** [comment]
No prob thanks for the effort! Unfortunatley I definitely broke the SAM timer somehow as its currently not working for me after trying the steps you just mentioned.

There was one instance where the timer activated in the middle of an update all script running (on the previous version), however at some point last night it the timer stopped working so SAM wont activate when sitting on the main menu. Ive been using the MiSTer_SAM_now script however cause the timer is broke somehow MiSTer just stays on the initial game loaded instead of going to the next core.

its a fresh .ini with the following:

# Time before Super Attract Mode starts in seconds
# 300 = 5 minutes, 600 = 10 minutes, 900 = 15 minutes
samtimeout=60

# Time before going to the next core in seconds
gametimer=120

# Start SAM only from MiSTer main menu
menuonly="Yes"

**Comment by mrchrisster** [comment]
Sorry to hear you're having so much trouble. The only thing I can think of for now is something going wrong with the joystick detection. So you have multiple device attached to your MiSTer?

**Comment by mrchrisster** [comment]
Just did some changes to the joy pad detection. Can you update and see if it works again?

**Comment by daemon5k** [comment]
it started on its own yay!!! thank you so much!!

Ill let you know if anything changes but I really love your work. its made my weekend much more fun.

**Comment by mrchrisster** [comment]
Awesome, glad it's working again :)
