### ISSUE TITLE
Can't skip to next game when only 1 core is allowed

### ISSUE THREAD

**Issue by Saroumane** [mrchrisster/MiSTer_SAM#212]
**To reproduce the problem :**
Let's say we want only arcade games in attract mode
We put this in MiSTer_SAM.ini :
`corelist="arcade"`
Then start SAM in "monitoring mode" to see what happens.

**Result :** SAM never moves to next game after the 1st one.

**Workaround :**
Use twice the same core in MiSTer_SAM.ini 
Example `corelist="arcade,arcade"`

**Suggestion :** this trick could be explained in the comments section of the MiSTer_SAM.ini file ?

**Comment by mrchrisster** [comment]
Thanks for reporting. This should be fixed now!

**Comment by Saroumane** [comment]
Indeed, it was a quick fix ! Thanks
