### ISSUE TITLE
Add option to ignore games that are require a vertical monitor rotation

### ISSUE THREAD

**Issue by TheRealBenForce** [mrchrisster/MiSTer_SAM#213]
I see a lot of games come up in SAM that require the monitor to be rotated 90 degrees. I like to keep these in my collection because sometimes I will want to play one and manually rotate through software. But during SAM, it would be great to just not select these titles.

**Comment by mrchrisster** [comment]
That's an option, check pathfilter in MiSTer_SAM.ini

**Comment by mrchrisster** [comment]
any success with pathfilter?
`arcadepathfilter="_Horizontal"`
should do the trick

**Comment by TheRealBenForce** [comment]
> any success with pathfilter? `arcadepathfilter="_Horizontal"` should do the trick

Just threw it in there. I'll keep an eye on it.

**Comment by TheRealBenForce** [comment]
> any success with pathfilter? `arcadepathfilter="_Horizontal"` should do the trick

Sorry I see this is in the readme now. 

One of the problems I'm having though is that only two or three games play before rotation stops so it is hard for me to test this. I noticed that the "Next game in" countdown never starts in these cases using the ssh mode. I have these settings but haven't learned anything that could help diagnose the issue other than the countdown not running:

samdebug="Yes"
samquiet="No"

I couldn't find a bug report for this. Any quick ideas or should I open one?

**Comment by mrchrisster** [comment]
Hmm strange. There are a couple things we can check..
First, make sure you update to the newest version.
Which cores do you have enabled? When rotation stops, check the files
`/tmp/SAM_Games.log` and `/tmp/SAM_game.mgl`

**Comment by mrchrisster** [comment]
Note: If you have a mouse connected and bump it, sam will stop. Same obviously for typing a key or pushiong a button. Could that be the issue?

**Comment by mrchrisster** [comment]
Ok, glad it's working now.
SAM should delete a core from corelist if no games for that system have been found. Please re-add the cores and check if the problem persists, that would be good to know.
Also, any samquiet output in ssh should be helpful

**Comment by TheRealBenForce** [comment]
The problem came back as soon as I added back default core list. Here are two examples:

**Example 1**
 Starting Super Attract Mode...
 Let Mortal Kombat begin!

 Selected core: GBC
Creating game list at /media/fat/Scripts/.MiSTer_SAM/SAM_Gamelists/gbc_gamelist.txt
Finding system folders...
Scanning GameboyColor: /media/fat/games/GAMEBOY
Indexing complete (0 games in 0s)
Can't find games for Nintendo Game Boy Color
 Selected core: ATARI2600
250 Games in list after removing duplicates.
Selected file: /media/fat/games/ATARI7800/BurgerTime.zip/BurgerTime (USA).a26
Starting now on the Atari 2600: BurgerTime (USA)
fgrep: /media/fat/Scripts/.MiSTer_SAM/SAM_Gamelists/gbc_gamelist.txt: No such file or directory
fgrep: /media/fat/Scripts/.MiSTer_SAM/SAM_Gamelists/gbc_gamelist.txt: No such file or directory
awk: /media/fat/Scripts/.MiSTer_SAM/SAM_Gamelists/gbc_gamelist.txt: No such file or directory
cat: /tmp/.SAM_List/gbc_gamelist.txt: No such file or directory
0 Games in list after removing duplicates.
sed: /tmp/.SAM_List/gbc_gamelist.txt: No such file or directory
fgrep: /tmp/.SAM_List/gbc_gamelist.txt: No such file or directory
Blacklist creation failed. Will try again on next core launch. Trying another rom...
fgrep: /tmp/.SAM_List/gbc_gamelist.txt: No such file or directory
cat: /media/fat/Scripts/.MiSTer_SAM/SAM_Gamelists/gbc_gamelist.txt: No such file or directory
 File not found.
Creating new game list now...
Finding system folders...
Scanning Atari2600: /media/fat/games/ATARI7800
Indexing complete (250 games in 2s)
cat: /tmp/.SAM_List/gbc_gamelist.txt: No such file or directory
Selected file:
awk: /tmp/.SAM_List/gbc_gamelist.txt: No such file or directory
 ERROR: Failed 1 times. No valid game found for core: atari2600 rom:
 Trying to find another rom...
Selected file: /media/fat/games/ATARI7800/Marine Wars.zip/Marine Wars (USA).a26
Starting now on the Atari 2600: Marine Wars (USA)

**Example 2**
 Starting Super Attract Mode...
 Let Mortal Kombat begin!

 Selected core: SMS
238 Games in list after removing duplicates.
Selected file: /media/fat/games/SMS/Baku Baku Animal.zip/Baku Baku Animal (Brazil).sms
Starting now on the Sega Master System: Baku Baku Animal (Brazil)
231 Games after removing blacklisted. (Next run of sms)
 Selected core: GBA
Creating game list at /media/fat/Scripts/.MiSTer_SAM/SAM_Gamelists/gba_gamelist.txt
Finding system folders...
Scanning GBA: /media/fat/games/GBA
Indexing complete (0 games in 0s)
Can't find games for Nintendo Game Boy Advance
 Selected core: NES
477 Games in list after removing duplicates.
Selected file: /media/fat/games/NES/Teenage Mutant Ninja Turtles II - The Arcade Game.zip/Teenage Mutant Ninja Turtles II - The Arcade Game (USA).nes
Starting now on the Nintendo Entertainment System: Teenage Mutant Ninja Turtles II - The Arcade Game (USA)
353 Games after removing blacklisted. (Next run of nes)
fgrep: /media/fat/Scripts/.MiSTer_SAM/SAM_Gamelists/gba_gamelist.txt: No such file or directory
fgrep: /media/fat/Scripts/.MiSTer_SAM/SAM_Gamelists/gba_gamelist.txt: No such file or directory
awk: /media/fat/Scripts/.MiSTer_SAM/SAM_Gamelists/gba_gamelist.txt: No such file or directory
cat: /tmp/.SAM_List/gba_gamelist.txt: No such file or directory
0 Games in list after removing duplicates.
sed: /tmp/.SAM_List/gba_gamelist.txt: No such file or directory
Blacklist creation failed. Will try again on next core launch. Trying another rom...
fgrep: /tmp/.SAM_List/gba_gamelist.txt: No such file or directory
fgrep: /tmp/.SAM_List/gba_gamelist.txt: No such file or directory
cat: /media/fat/Scripts/.MiSTer_SAM/SAM_Gamelists/gba_gamelist.txt: No such file or directory
 File not found.
Creating new game list now...
Finding system folders...
Scanning NES: /media/fat/games/NES
Indexing complete (477 games in 0s)
cat: /tmp/.SAM_List/gba_gamelist.txt: No such file or directory
Selected file:
awk: /tmp/.SAM_List/gba_gamelist.txt: No such file or directory
 ERROR: Failed 1 times. No valid game found for core: nes rom:
 Trying to find another rom...
Selected file: /media/fat/games/NES/Teenage Mutant Ninja Turtles II - The Arcade Game.zip/Teenage Mutant Ninja Turtles II - The Arcade Game (USA).nes
Starting now on the Nintendo Entertainment System: Teenage Mutant Ninja Turtles II - The Arcade Game (USA)

**Comment by TheRealBenForce** [comment]
Closing this since the conversation beyond the original reported issue which is configurable in the ini.

**Comment by mrchrisster** [comment]
can you check if this problem is gone now? cores without games will now be removed from the ini and shouldn't cause any output anymore.

**Comment by mrchrisster** [comment]
please try
https://github.com/mrchrisster/MiSTer_SAM/blob/b30f266aa52e82dea66039489c3357b5848b2d5a/MiSTer_SAM.ini#L95

**Comment by TheRealBenForce** [comment]
@mrchrisster , sure thing. will let you know.

**Comment by TheRealBenForce** [comment]
@mrchrisster sorry haven't had much time to mess with it. It seems to be working, although its not really clear to me what it does. Like what if I didn't want to use "0". What happens if I use something different. So some info in readme could be helpful maybe. Also I notice this error now in ssh mode that I didn't notice before, but it doesn't seem to have an affect on selection.

`shuf: invalid input range: ‘’`

**Comment by mrchrisster** [comment]
I just uploaded a new version. Can you turn samdebug on in the ini? It should give you more insight what's it doing

**Comment by mrchrisster** [comment]
Would be interesting to know how your core distribution looks like.

**Comment by mrchrisster** [comment]
It should give you a percentage of how likely it is that a core gets selected

**Comment by mrchrisster** [comment]
So it turns out the shuf error was unrelated but is fixed now as well.
You have to enable 'coreweight=yes' in ini or use the new settings feature in the menu and go to miscellaneous options -> enable alternative core selection mode.

**Comment by TheRealBenForce** [comment]
Seems to be showing the % now correctly, that's cool thanks! When it pulls arcade games though every time I'm getting "no rbf found" on the screen. I never noticed this before, I definitely had arcade cores playing properly.

**Comment by mrchrisster** [comment]
Try deleting the gamelists through the menu

**Comment by TheRealBenForce** [comment]
Not sure what happened but all my rbf files were missing. Reran update_all and all is well in the mister world again.

**Comment by mrchrisster** [comment]
Good to hear - and SAM is definitely not deleting Rbf files ;)  Still curious about your core percentage if you get a chance to post it.

**Comment by TheRealBenForce** [comment]
@mrchrisster here you go. This what you are looking for?
```
[genesis] = 28
[snes] = 24
[nes] = 18
[arcade] = 15
[sms] = 12
```

**Comment by mrchrisster** [comment]
Just curious if the values make sense for other setups, looking good
