### ISSUE TITLE
Request: Way to have a single game load immediately on boot.

### ISSUE THREAD

**Issue by janimator0** [mrchrisster/MiSTer_SAM#215]
Is there a way to have a specific game load immediately on boot?

**Comment by mrchrisster** [comment]
With SAM, you will need to wait for 2 minutes before it starts cycling.
If you want to boot in a game on startup, check [this](https://misterfpga.org/viewtopic.php?t=4465) thread.

If you still want to have SAM start after 2 minutes you will have to set menuonly=no in MiSTer_SAM.ini

**Comment by janimator0** [comment]
Thanks for pointing me in the right direction!
