### ISSUE TITLE
BGM stops when switch to the next game

### ISSUE THREAD

**Issue by tron303** [mrchrisster/MiSTer_SAM#216]

**Comment by tron303** [comment]
I guess it is because of the Monitor. Audio came via hdmi, and then via headphone-jack to the speakers.

**Comment by mrchrisster** [comment]
hey there thanks for the bug report. I was able to replicate this issue once, but reinstalling BGM fixed it for me. Did you try from the SAM menu -> Settings -> Background Music Player ?

**Comment by tron303** [comment]
I guess, switching cores is the problem. This breaks the signalchain.

**Comment by mrchrisster** [comment]
Have you tried reinstalling bgm from the menu?

**Comment by tron303** [comment]
> hey there thanks for the bug report. I was able to replicate this issue once, but reinstalling BGM fixed it for me. Did you try from the SAM menu -> Settings -> Background Music Player ?

Yes, I use it via sam.

**Comment by tron303** [comment]
yes, reinstalled it to. I guess there is nothing we can do.
If cores are switching, the analog-audio-out will be resetted in some kind of way, so that the signal-flow is (peaked) interrupted. It's like rebooting the MiSTer.

**Comment by mrchrisster** [comment]
Oh i think I know now what you mean. I thought bgm does not continue playing on the next core but you mean, core switching causes bgm to interrupt.

Yes, you're right there is nothing that can be done. There will be a short interrupt with bgm when switching to the next core.

**Comment by tron303** [comment]
also, if you got you audio digital via hdmi, than this process could even get longer, because the screen-output is resetting to, to the Screen normally resets itself to the new conditions before the audio is hearable (>1-2s)

**Comment by tron303** [comment]
so i guess, this case is cold and closed. Known core problem, no solution ahead ;-)

**Comment by mrchrisster** [comment]
Unfortunately yes 😉
