### ISSUE TITLE
Choosing a default video processing during attract mode

### ISSUE THREAD

**Issue by felleg** [mrchrisster/MiSTer_SAM#218]
Hi!
I'm trying to figure out how to edit the default video processing option and orientation (when applies) during attract mode. For example, unless configured otherwise per core, I'd like to use medium scanlines for all cores. Where should I go to specify something like this? I'm not quite sure where this information is stored on the device or if there's some script that could give me access to it.

Thanks :) Attract mode 60 sec per core rules, thanks for the great work!

**Comment by mrchrisster** [comment]
Hey sorry for the late reply. Is this still an issue? SAM does not touch video settings so it should be the same as when playing games

**Comment by felleg** [comment]
It's been a while since I gave this a try, I'll close it for now. Someone can re-open this issue if they want.
