### ISSUE TITLE
Using blacklists

### ISSUE THREAD

**Issue by felleg** [mrchrisster/MiSTer_SAM#219]
Sorry if this is a stupid question, but how do blacklists function? I was browsing commits and I came across this script: https://github.com/mrchrisster/MiSTer_SAM/blob/main/.MiSTer_SAM/sp/blacklist_maker.sh

How do I know if blacklists are enabled for me? How to I enable/disable them?

**Comment by mrchrisster** [comment]
Hey hey, sorry just going through the issues and saw your message. 
blacklist_maker is just my own tool to use with the hdmi capture card I have connected to my mister. It helps me automated the process of capturing every game for a core to create the blacklists.
Blacklists are always enabled by default.
