### ISSUE TITLE
Feature Request: Add 'ignore' key to script

### ISSUE THREAD

**Issue by stopmosk** [mrchrisster/MiSTer_SAM#220]
Hi

It would be great to add the `ignore` argument to the SAM script so that the currently playing core is not just skipped (`skip | next`), but added to the ignore list and is no longer available.

**Comment by mrchrisster** [comment]
Added in the most recent release. You can ignore a game now by issuing:
'/media/fat/Scripts/MiSTer_SAM_on.sh ignore'
or through SAM's menu

Steps to check if it is working correctly:
1. Start with a fresh boot
2. Start SAM by waiting or launching it with '/media/fat/Scripts/MiSTer_SAM_on.sh start'
3. Issue '/media/fat/Scripts/MiSTer_SAM_on.sh ignore'
4. Check that '/media/fat/Scripts/.MiSTer_SAM/SAM_Gamelists/CORENAME_excludelist.txt' was created with right game.
5. Reboot MiSTer and start SAM again.
6. Now check with `cat /tmp/.SAM_List/arcade_gamelist.txt | grep -i "excluded game"` if game is missing

**Comment by stopmosk** [comment]
Hi! Thank you for the new feature!

I went through the steps: 1-5 finished as you described, but I cant understand step 6. What do I get with it? Nothing was changed after it in my case.

**Comment by mrchrisster** [comment]
Of the command completes without showing anything it means that the game is missing. If you have trouble with grep you can also just open that file ( /tmp/.SAM_List/arcade_gamelist.txt ) to see if your game is not on that list

**Comment by mrchrisster** [comment]
Feature seems to be working well for me so I'm closing the issue for now. Please re-open if you encounter any issues
