### ISSUE TITLE
suggestion: mode that only plays roms with (Demo) and/or (Kiosk) in the filename 

### ISSUE THREAD

**Issue by liljordo** [mrchrisster/MiSTer_SAM#221]
SAM is one of my favorite features of the MiSTer FPGA and I love letting it cycle while I work on other tasks. It occurred to me recently that many of the roms for demo/kiosk versions of games are available, and that these roms often have unique attract modes as compared with the final release versions. It would be great if SAM were able to look for common flags in the filename like (Demo) or (Kiosk) and only load those files when selecting a new game, replicating the store kiosk experience at home.

My apologies if this is already somehow possible! Thanks for the work you do on SAM, it is very much appreciated.

**Comment by mrchrisster** [comment]
Interesting idea. I was looking through some of SAM's gamelists just now and saw kiosk roms mostly for the GBA library. Are there other cores besides GBA where this would be useful?

**Comment by liljordo** [comment]
Thrilled to give this a try, thank you so much!
