### ISSUE TITLE
Configurable/Variable Scrolling Speed and/or Name Options?

### ISSUE THREAD

**Issue by rayman147** [mrchrisster/MiSTer_SAM#222]
Hi mrchrisster! I continue to be blown away by how well SAM is working. It's awesome. I have been using the extra tty2oled options (THANK YOU so much for those!), and thought I'd suggest another update, if it's possible:

Can we have a set of options for the speed at which tty2oled scrolls the name of the game? With the bigger font, which is great, many of the longer names take so long to scroll that it can be confusing and/or frustrating as you're waiting for it to cycle back. I'd love to be able to speed it up.

Thanks also for the kid-friendly flags! Awesome. Keep on rocking it. :)

**Comment by rayman147** [comment]
Another related thought as I'm thinking about reducing what is displayed on the tty2oled device: would it be possible to parse the ROM/Game name and filter out characters/strings so we can avoid displaying unwanted/needed stuff on the tty2oled device? Maybe call the flag 'tty2oled_name_hide' and have it work in a similar fashion as the folder & file exclusion option... some examples off the top of my head might be:

tty2oled_name_hide=( JPN NTSC PAL '(USA)' '(PAL)' )

In the above example the various region strings would be removed from the game name entirely.

If feasible, maybe even set up a limited 'find and replace' method, maybe using a pipe character? Where SAM would replace the string on the left of the pipe with what is on the right? Sort of like:

tty2oled_name_replace=( 'find|replace' '_| ' )

So in the above example, 'find' would be replaced by 'replace' in the game name showing on the tty2oled device, and any underscore would be replaced by a space. This would give some additional granular control over how game names are displayed.

NO worries if this is a step beyond, but it may be a fun way to further configure things in a super nerdy way ;)

**Comment by rayman147** [comment]
OK, final mind dump about this (Fridays are my day to muck about with my MiSTer and update things and I'm having fun tweaking MiSTer_SAM settings today, LOL). It would be pretty cool to simply have the option to remove common 'non essentials' from game names, such as any parenthetical items. Lots of times there are date strings in between parentheses in names, like (12345678) or (USA), (JPN), etc. It would also be great to just have a basic option to replace underscores with spaces too. I still LOVE having granular control as mentioned above but a few basic options may make it easier for a wider user base to tweak things to be more readable on the tty2oled.  Thinking something like:

remove_name_parentheticals=yes
replace_name_underscores=yes

or even (if you wanted to create an internal list of common region makers):

hide_region_info=yes

or if you wanted to roll all of this stuff into a single option/flag maybe something like:

name_cleanup=yes

**Comment by mrchrisster** [comment]
Hey hey, thanks for your suggestions! It's always great to hear when people use SAM and feature requests are always welcome. Unfortunately we can only make the tty2oled speed slower, it is currently set to update as fast as possible. I'll play around with it when I have some time to see if there is a trick to speed it up.

For now I have implemented a new option: ttyname_cleanup=yes removes all brackets

**Comment by rayman147** [comment]
Hi Christoph!

Thanks, I'm so glad you're encouraged – SAM is *amazing* and brings a lot of joy to our house. :) Not just to me, but my kids, their friends and other folks who head in to see 'the museum.' Thank you for all you do!

AWESOME and thank you for the cleanup option! :) I can't wait to check it out tonight.

Take care,

Matt Schroeder

**Comment by rayman147** [comment]
I'm so encouraged by all the work you're putting in!! SAM is really special. :) I LOVE the scroll speed - looks like some frame skipping was the ticket? Looks GREAT. I noticed a few things that aren't a huge deal but for what it's worth:

• Some cores (PSX in particular) don't seem to scroll text, while others do. Not sure why.
• I'm still noticing bracketed info - stuff in between [ xx ] brackets and even a few ( xx ) parenthetical things still showing up, but not sure why. 
• I was pulling from the 'test' branch in the .ini file, but wasn't seeing the latest updates working so I went back to the 'main' branch and then it all worked. Probably best for me to stick with the main I'm guessing.

Seriously - amazing work. Thank you!

**Comment by mrchrisster** [comment]
Hey rayman, thanks for your feedback. 

I actually just pushed the new samvideo functionality from test branch to main. It plays video game commercials in between other cores. If you update and check in the menu under add ons, you can activate it. I'd appreciate any feedback since I haven't been able to test it much yet. 

I'll look into the other issues. The double speed seems to be hit and miss. I got some reports it's stopping the display from working for a while so I switched mine back to normal speed.
The PSX not scrolling issue is strange since it's running the same code as all the other cores. Maybe it's related to the double speed setting?

**Comment by rayman147** [comment]
Hi Christoph! You're most welcome. That samvideo functionality sounds INCREDIBLE! I keep a playlist of old game commercials on an Android TV device connected to my CRT, it would be MUCH better to utilize SAM for it. I'll check that out right away and give you feedback for sure. Very cool!

I'll have to try changing some settings and do more tests to see if I can isolate the behavior for what I'm experiencing with the scroll, I haven't looked too closely into it but noticed that PSX games just didn't seem to scroll. Might take me a few days as I'm swamped with work (and graduating kids LOL) but will loop back in once I've had some time to test. I was telling my wife how impressed I am with the work you've done on this - thanks again for all you do!

**Comment by rayman147** [comment]
I saw it was wizzo's module as it installed, VERY cool. Super encouraging to see the community come together on this. Ah, thanks for the list - I should have looked deeper but trying to work at the same time, super distracting and fun watching my CRT today LOL - yeah, perhaps my son and I can try to create a segmented list of commercials and speedruns. :)

**Comment by mrchrisster** [comment]
That would be cool, thanks :)

**Comment by rayman147** [comment]
you got it. Let me know what issues you see - I've only had a chance to watch a handful of the videos but it does appear that there's some sync-issues on my CRT, wavy horizontal video that I originally thought was part of the video itself (from a bad VHS rip or something) but now I think it's probably just video issues. Not so bad as to wreck the experience but probably should be more stable. If you want some video of it let me know and I can upload a clip, but my guess is you're aware.

**Comment by mrchrisster** [comment]
I used video mode settings that work on my CRT, so I'm glad they work on yours as well! You can customize them in MiSTer_SAM.ini if they appear stretched. If you switch to archive streaming in the settings, they are more curated and also appear in a higher quality.
