### ISSUE TITLE
menuonly="No" needs a timeout value. Currently disrupts gameplay mid-game play.

### ISSUE THREAD

**Issue by alexanderupton** [mrchrisster/MiSTer_SAM#224]
When testing menuonly="No"  the expected functionality is that when you've stopped playing a game (no controller input) for an unknown period of time the current core would exited in favor of the SAM executed core. 

I have experienced the following issues:

1) SAM exiting a game mid-play
2) SAM exiting a game that had just been activated via the playcurrentgame="Yes" after about 20 seconds of gameplay.

I suspect both of these would be resolved if menuonly= had an accompanying menuonly_timeout= option. The thought here is if we can define the inactivity of gameplay timeout then when using on an arcade machine if someone walks away after the timeout has ended, then the current active game would exit in favor of SAM.

Great work on this tool, infinitely better than the version I wrote. Thank you.

**Comment by mrchrisster** [comment]
Hey Alex, thanks for your feedback. 
You can set the timeout with the first setting in the ini:
```# Time before Super Attract Mode starts in seconds. On reboot it will wait an additional minute for all services to load up.
# SAM comes on at 60s + samtimeout, so default is a 2 mins wait in main menu before SAM starts.
# 300 = 5 minutes, 600 = 10 minutes, 900 = 15 minutes
samtimeout=60```

**Comment by alexanderupton** [comment]
Hello, thanks for your reply. I'm not seeing samtimeout being respected when menuonly=no and this doesn't address issue where SAM is triggering while a game is actively being played and menuonly=no. 

listenkeyboard="Yes" and listenjoy="Yes" are both set.

**Comment by mrchrisster** [comment]
Oh sorry, I misunderstood. Let me look into it!

**Comment by mrchrisster** [comment]
I submitted one quick fix. Please update SAM and see if it fixes the issue.
