### ISSUE TITLE
Next game button feature request

### ISSUE THREAD

**Issue by flain2** [mrchrisster/MiSTer_SAM#225]
Hi, firstly thanks for your work on this, it is awesome. I use it frequently on arcade machines i have, and it has enticed people to sit down and play when something interesting has come up.

Would it be possible to add a feature to press a button to force SAM to cycle to the next game? Currently there is a feature to configure the controller so that pressing start will play the current game, so ideally it would be also an input from a controller but would trigger the next random game to be loaded up rather than waiting for the timer to do it.

The usecase here is in an actual real neogeo cabinet has a "next game" button which usually cycles through carts/games plugged into the board. It would be awesome if i could press the next game button and have MiSTer go to the next game.

**Comment by mrchrisster** [comment]
Cool idea! I'm on vacation for the next 3 weeks but I'll see what I can do when I come back

**Comment by mrchrisster** [comment]
This has been implemented.
https://misterfpga.org/viewtopic.php?p=83868#p83868

Please let me know if it works.
