### ISSUE TITLE
BGM in menu, but video/game audio from SAM

### ISSUE THREAD

**Issue by manyhats-mike** [mrchrisster/MiSTer_SAM#226]
I'm trying to figure out how to get this specific setup:
- Play BGM (from a playlist) while navigating through the menu system
- Stop BGM when SAM kicks in, as I want to hear the audio from the game commercials and gamplay
- When SAM terminates, resume BGM

I haven't been able to figure out how to configure it this way, is it possible?

**Comment by mrchrisster** [comment]
I did some updates to the bgm module. Can you test and let me know please?

**Comment by manyhats-mike** [comment]
Tested this out and it seems to be working great!  Was able to have my 80's music streaming during navigation, then I loaded up the new "greatest of all time attract mode".  Afterwards I got back to the menu to navigate with music again seamlessly.  Thanks for this sweet update!!!

**Comment by mrchrisster** [comment]
Awesome, thanks for letting me know and sorry it took a while to address this.
