### ISSUE TITLE
SAM Script Causes Display Issues on CRT: Black & White Output and Aspect Ratio Problems

### ISSUE THREAD

**Issue by manyhats-mike** [mrchrisster/MiSTer_SAM#227]
Environment:

MiSTer setup with the Analogue IO Board
YC Active Encoder board (supporting S-video and composite)
Sony KV-27S42 Trinitron CRT
Connection: Composite between the YC Active Encoder and the CRT
All components are updated with the "update-all" script

Expected Behavior:

Full color display on the MiSTer frontend and correct output for all game cores on the CRT after running the SAM (Super Attract Mode) script.

Actual Behavior:

After enabling the SAM script and a system reboot, the display turns to black and white on the MiSTer frontend. While the ability to change wallpapers is now possible (which was not the case prior to installing the SAM script), the output seems distorted. Moreover, any game core launched post-SAM activation displays in black and white with an incorrect aspect ratio.

Steps to Reproduce:

Run the "update-all" script on the current setup.
Verify the full color display on the MiSTer frontend and correct output for all game cores on the CRT.
Run and enable the SAM script.
Observe the change to black and white display on the MiSTer frontend post-reboot, along with the ability to change wallpapers.
Launch a game from any core and notice the black and white display along with an incorrect aspect ratio.
Supporting Information:

I suspect there may be an alteration or addition to the MiSTer.ini file via the SAM script that conflicts with my specific setup. I'll aim to provide the ini files pre and post script running for further analysis. Meanwhile, I've captured the issue in two videos:

[Running the SAM script and observing the result](https://youtu.be/yWT9TRvFyjY)
[Launching a game after running the SAM script](https://youtube.com/shorts/kToM1C3TBGQ?feature=share )

Temporary Fix:

Deleting the MiSTer.ini file, reconfiguring my settings, and disabling SAM reverts the display back to its correct form.

**Comment by mrchrisster** [comment]
Thanks for your detailed report. Did you enable samvideo by chance? Samvideo requires the settings for your CRT to work. 
https://github.com/mrchrisster/MiSTer_SAM/blob/5f4635f28d4b9a8990534645898f0d06752de324/MiSTer_SAM.ini#L115

**Comment by manyhats-mike** [comment]
Yes, I am using Samvideo.  I have set the mode to "CRT" but perhaps I have
missed a setting?  I have attached my current MiSTer_SAM.ini file here,
along with my MiSTer.ini file

**Comment by manyhats-mike** [comment]
[ini_files.zip](https://github.com/mrchrisster/MiSTer_SAM/files/12115328/ini_files.zip)

**Comment by manyhats-mike** [comment]
Here's the diff of my ini file before and after, this is likely the culprit
❯ diff MiSTer.ini MiSTer.ini.bad
321c321,325
< ;controller_unique_mapping=0
\ No newline at end of file
---
> ;controller_unique_mapping=0[menu]
> video_mode=640,16,64,80,240,1,3,14,12380
> fb_terminal=1
> vga_scaler=1
> 

I think all three of those settings are incompatible with my setup.  My CRT can't use vga_scalar from my understanding, and I need to set the fb_terminal to 0.  Not sure about the video_mode setting.

**Comment by manyhats-mike** [comment]
Apologies, just picked up my MiSTer yesterday so still learning how things work.  Got a better understanding now.  Reviewing the changes that get made to my config from the script, I think the bug is probably here:
;controller_unique_mapping=0[menu]

It looks like it might need to add a newline '\n' before inserting the [menu].  What appears to be happening is that the [menu] gets appended to the last line of my config file, so its affecting things outside the menu which explains why my games started having a strange aspect ratio.  Probably if I had an empty line at the bottom of my config it would work correctly.

Besides that, the rest would just be an issue with my CRT TV.  Understanding a bit more about the settings now, I would have to figure out the appropriate video_mode for my TV and adjust the MiSTer_SAM.ini on this line:
samvideo_crtmode640="video_mode=640,16,64,80,240,1,3,14,12380"

Since I had it set to stream from the archive.

**Comment by mrchrisster** [comment]
Thanks for investigating. That indeed seems like a bug. I'll look into it!

You can try these settings for your CRT
```[Menu]
video_mode=640,-16,56,56,240,1,3,13,11350
vga_scaler=1```

**Comment by mrchrisster** [comment]
Just modified the command to add a new line before adding the [menu] item. Have you had any luck with the crt mode?

**Comment by manyhats-mike** [comment]
> Just modified the command to add a new line before adding the [menu] item. Have you had any luck with the crt mode?

I did, thank you!  I've got a much better understanding of the MisTer now.  My issue was all due to the fact that I was running my CRT on composite, which does not support the vga_scaler or fb_terminal options.  I switched to a CRT monitor with VGA input and have no issues.  The other CRT is going in for an s-video mod :-)
