### ISSUE TITLE
blacklist criteria / usage ?

### ISSUE THREAD

**Issue by Saroumane** [mrchrisster/MiSTer_SAM#228]
First of all : thanks for your awesome work !

Regarding blacklists, I read that : 
_Curated Blacklists - The SAM Team is currently recording every game's attract mode to short videos that we capture through HDMi so we can detect if a game is worthy to be shown or should be blacklisted (like Disc 2 for MegaCD, load error FDS games or games with a static screen)_

And I see that indeed 15642 core/games are blacklisted (by default, I did not do anything)
```
/media/fat/Scripts/.MiSTer_SAM/SAM_Gamelists# wc -l *black*
  3281 amiga_blacklist.txt
   138 arcade_blacklist.txt
   504 fds_blacklist.txt
  1846 gba_blacklist.txt
  1190 genesis_blacklist.txt
    88 megacd_blacklist.txt
    27 neogeo_blacklist.txt
  4069 nes_blacklist.txt
   472 psx_blacklist.txt
    59 s32x_blacklist.txt
   869 sms_blacklist.txt
  2625 snes_blacklist.txt
   328 tgfx16_blacklist.txt
   146 tgfx16cd_blacklist.txt
 15642 total
```

=> Could you please elaborate about the criteria you used to blacklist a game ?
=> If I want to blacklist some additional games, I understand it's recommended to have my own file in this folder ? 
=> Does the name of the file matter  ? Can I name it "myblacklist.txt" and mix games from different cores in it ? Or it should be named as "name_of_the_console/computer_blacklist_xxx.txt" ? Could I used 2 blacklist files for arcade (yours and mine) ?

Thanks for your help.

**Comment by mrchrisster** [comment]
Sorry, somehow missed your post! Blacklisted are games with static screens that don't offer an attract mode. To create the blacklist every single game from a core's library is recorded into a video and then checked by a script for scene changes.
If you want to exclude your own games, please follow the instructions on the main GH page (search exclude)
