### ISSUE TITLE
Feature request: Nintendo M82 demo unit mode

### ISSUE THREAD

**Issue by Yamato-san** [mrchrisster/MiSTer_SAM#230]
Hi there and thank you very much for this awesome script!

I‘d like to make a suggestion: Wouldn‘t it be cool to let the SAM act like a Nintendo M82 demo unit? It‘s almost there, however there are missing key features I guess.

The M82 autoboots into the M82 splash screen, which is available as a .nes rom, so no problem here. The tricky part is that the splash screen plays for 20 seconds (without any controller input) and then jumps directly into the first of the 12 inserted nes games. If there happens to be no controller input for again 20 seconds it jumps back to the M82 splash screen. Then it jumps to the next game after 20 seconds and so on. Controller inputs set the M82 into play mode. Play time can be set to 30 seconds, 3 minutes, 6 minutes or 128 minutes. 

I guess you could make good use of the game roulette mode and maybe a subfolder with your selection of nes games that SAM will use only. Hoewever, these games should cycle through one by one and not randomly. Of course games in that directory could be named „1 Super Mario Bros“, „2 The Legend of Zelda“ and so on, so it will have a certain order like in the original M82.

Additionally it would be necessary to make this interchanging splash screen - game 1 - splash screen - game 2 - splash screen and so on a configurable option.

Lastly, a „Jump to next game by pressing a button“ feature would make it perfect like on a real M82 (see also https://github.com/mrchrisster/MiSTer_SAM/issues/225).

Thanks for reading :-)

Best regards!

**Comment by mrchrisster** [comment]
Great idea! I implemented a first idea for M82 mode. It doesn't have controller input functionality yet. You can update SAM and enable from the menu or the ini.

**Comment by mrchrisster** [comment]
This has been fun to get it working. I believe all features are implemented now.
- Timer is set to 22 secs and can't be changed
- the ini now has an option to change the gametimer
- the next button is working during m82 bios and games but when on m82 bios you can't "play" it anymore
- please follow controller config precisely (only have one controller connected during setup and reboot after) - it should work. I tested on 2 different MiSTers with two different gamepads and was able to remap both.
- startup from cold boot for m82 mode is fixed

**Comment by Yamato-san** [comment]
Wow, you pretty much nailed every point with the recent update! Thank you very much :)

Faulty controller mapping was my fault, sorry. Seems I forgot to reboot. I suggest to include this piece of info in the on screen text box which appears during the process. It‘s there when you set playcurrentgame to „no“ like recommended, but it does’t get mentioned when you leave it as it was.

Here are some more observations and suggestions:

- 21 seconds really is closer to original hardware. Music plays significantly too long now. At least for me as a nerd ;) No sync issues here though. Sorry for being so puristic about this :)

- I just noticed that the first M82 bios animation after launching the script always plays several seconds longer than any other afterwards. Is this expected / fixable?

- While being on the last game from the list, the „Next Game“ button should jump back to game 1 and not the initial bios screen. It‘s the same with the original M82 :)

While re-reading my last comment regarding Super Mario Bros. and „Next Game“ button, I noticed that I made a wrong assumption, so please ignore that. Because the M82 had a separate button for selecting the next game it is good the way it is as the „Next Game“ button has to be functional all the time. I will just use a gamepad with more buttons instead of my NES style gamepad so I‘ll have a separate button for selecting games.

One thing though:

- Is the Next Game button kind of picky? Because pressing it very quickly does‘t jump reliably to the next game for me. Pressing it just a tiny bit longer does (intended?). Also it‘s not functional the moment a new game loads. It takes like 2 to 3 seconds or so (expected?). Sometimes I had to press twice. Don’t know what’s going on sorry :) Tested different controllers too.

Again, thank you so much!

**Comment by mrchrisster** [comment]
I pushed a commit to fix the next button sometimes not responding. I'll check on the other issues when I got some time tonight

**Comment by Yamato-san** [comment]
Great update!

+ Initial bios screen is not longer than the following ones anymore :)

+ bios screen length seems to be shortend back to 21 seconds and is as close to original M82 as possible now (at least without fractional digits) :)

+ Last game now jumps back to game 1 and not to bios screen anymore :)

+ Game timer works on last game for me now :)

+ Next button is by far more reliable now :)

I‘d say M82 mode is pretty much perfect now. You are awesome! Thank you so much!

**Comment by mrchrisster** [comment]
Great stuff! I was playing a lot of old favorite NES games while checking m82 mode. Thanks for the fun challenge to get this working. If you discover any other bugs, lmk. Otherwise please go ahead and close the feature request.
