### ISSUE TITLE
tgfx16-cd does not start games

### ISSUE THREAD

**Issue by Saroumane** [mrchrisster/MiSTer_SAM#233]
For the tgfx16-cd core, it seems that MiSTer_SAM does not pass the "RUN" title screen.
I read somewhere that the workaround is to use a tgfx16-cd bios that "autoruns" CD games.
Does this BIOS exist . What could be its name ?
Thanks !

**Comment by mrchrisster** [comment]
I can't replicate your problem. There is a autostart bios out there, but with the standard update_all pulled rom tgfx16cd starts after about 10s showing the run command

**Comment by Saroumane** [comment]
Hi, I think I can replicate the problem.

From a fresh install with latest of the TGFX core (TurboGrafx16_20240419.rbf), if I activate SAM on tgfx16-cd core, I have CD Games auto starting after around 10 sec.

So far, so good.

But when I activate (in the core, "Hardware submenu) the option "User I/O   SNAC",  it no longer autostarts games.
SNAC activation seems to prevent the "RUN" simulated keypress in attract mode.

Do you think it can be "fixed" ? (Meaning : keeping SNAC activated and SAM working for tgfx-16cd games ?)

**Comment by mrchrisster** [comment]
Ah that makes sense! SNAC controllers don't work with SAM. SAM sends a virtual gamepad command to start the game which can't be done when SNAC is active. Sorry there is no fix possible since SNAC doesn't use Linux. 
You can still use an auto boot bios for TGFX16CD though.
