### ISSUE TITLE
blacklist sinden cores

### ISSUE THREAD

**Issue by drackybrok** [mrchrisster/MiSTer_SAM#236]
The mister sinden light gun cores need to be omitted from booting non-light gun games.

**Comment by mrchrisster** [comment]
Hey there, I don't have those cores. Do you want to create a PR?

**Comment by drackybrok** [comment]
I was just submitting feedback I have no idea about any dev stuff I just thought I would be nice if you could blacklist the sinden cores from booting unless that's already a feature somewhere that I missed?

**Comment by mrchrisster** [comment]
I talked to wizzo and he ran into the same issue. In future versions Sinden cores will therefore be in their own folder and shouldn't cause any issues anymore. 
The way SAM structures the mgl is to MiSTer's specifications so there is nothing that can be done to SAM, best is to wait for Sinden cores to be changed to comply.

**Comment by drackybrok** [comment]
Thank you for the info. Keep up the good work!
