### ISSUE TITLE
Issue setting GOAT as standard mode

### ISSUE THREAD

**Issue by hapimp** [mrchrisster/MiSTer_SAM#237]
Thanks for creating SAM, it's definitely an awesome plugin! I am trying to set standard mode to GOAT, but it defaults to the standard mode after a restart. This happens if I use the toggle in the SAM menu or if I edit the config file. Is this intended behaviour or am I maybe doing something wrong?

**Comment by mrchrisster** [comment]
Let me look into this! Might take me a day or two

**Comment by hapimp** [comment]
Awesome, thanks. Let me know if I can help test in any way

**Comment by mrchrisster** [comment]
I believe this should be fixed now. Could you give it a try?

**Comment by hapimp** [comment]
Yep everything seems fine here now, thanks for the fix!
