### ISSUE TITLE
Mister hangs on "Stopping other running instances of MiSTer_SAM_on.sh..."

### ISSUE THREAD

**Issue by djEatch** [mrchrisster/MiSTer_SAM#238]
Install seems to go fine until the final line: Stopping other running instances of MiSTer_SAM_on.sh...
IT then hangs on this and requires a power cycle to get back to the main menu.

Trying to run SAM_On from the main menu and allowing it to auto configure results int eh same.

It works fine on my other mister, but annoyingly not the one that's sat inside a cabinet with no easy access to the SD or user buttons... (FTP and SSH are available though).

I have tried reinstalling via the config menu, but again, no difference.
I'm probably doing something stupid, but it's configured almost identically to the working mister - just with a bigger SD card.

**Comment by mrchrisster** [comment]
After the restart, does SAM activate after a few minutes?

**Comment by djEatch** [comment]
It doesn't appear to. 
If i run SAM_on, and press up for the menu, it just exists out.
If i run it and leave it to auto configure, it gets stuck at the same point.
If i run it and press down to launch immediately then it hangs at the same point.
I left it on for a good hour, and it did eventually end the hang and launch the first core - but then it never moves on to another, even though it's configured for 180 seconds...
(I'm tempted to rebuild my SD card, but it's a hassle to get into the cabinet, and the games work....)

**Comment by mrchrisster** [comment]
Hmm, yeah sorry that sounds like a corrupted SD. Maybe try to reset SAM from the menu and see if that helps?

**Comment by djEatch** [comment]
No worries. Thank you for looking into it. I'm probably going to put off rebuilding it until the cores start failing (and then maybe go for a usb or even a nas setup to share across the pair)

**Comment by mrchrisster** [comment]
Sorry I couldn't be of more help. See if you can run update_all and enable it to update SAM. Hopefully that fixes it. USB setup is a good idea if you want PSX/Saturn library
