### ISSUE TITLE
NeoGeo  problem.

### ISSUE THREAD

**Issue by neosquid** [mrchrisster/MiSTer_SAM#24]
NeoGeo Games which normally launch fine in MiSTer seem to report a "Z80" error when MiSTer_SAM is attempting to launch the game.

**Comment by mrchrisster** [comment]
Neogeo is unfortunately not very compatible with our helper tool, mbc. Does this happen for you with every game?

**Comment by Mellified** [comment]
This does happen to me with every NeoGeo game. I am running via CIFS.

**Comment by neosquid** [comment]
I'm running from SDCARD only. It seems that every game will report the Z80 error as the script attempts to load games in attract mode.

**Comment by mrchrisster** [comment]
updated to a new version of mbc and currently testing to resolve this issue

**Comment by mrchrisster** [comment]
@neosquid can you update and let us know if you still have this issue?
It might be your romset/bios files

**Comment by neosquid** [comment]
Yes. When the script launches a negeo game, during the initial MiSTer loading process it reports  Loading """.neo

Games launch no problem outside of the script.

**Comment by mrchrisster** [comment]
Are you using .neo files unzipped?

**Comment by neosquid** [comment]
The problem is probably I'm using unzipped neogeo games - I don't actually have .neo files!

**Comment by mrchrisster** [comment]
.neo is required for Sam to work.

**Comment by neosquid** [comment]
Hello again, I converted my neo geo roms to .neo files. 
Now, when running the SAM script,  it only seems to open the Neo Geo core Mister OSD load game option.

**Comment by pc-2198x** [comment]
I have this issue. All files end with .neo. SAM when hits a NeoGeo game only shows a white screen. I have everything on CIFS, only NeoGeo causes me a problem.

**Comment by mrchrisster** [comment]
Hey there, Neo Geo is hit and miss unfortunately. It doesn't always work and when you check the presets folder here on the SAM GitHub, you'll see i disabled a bunch of my Neo Geo games that didn't launch. Our hope is that once MRA is supported officially by the core, we can switch to that.
Do games launch outside of SAM for Neo Geo?
I have my games on CIFS as well and Neo Geo launches fine.

**Comment by mrchrisster** [comment]
You might want to look for another set of roms in this case. Google "archive htgdb" and see what you find. Good luck ;)

**Comment by pc-2198x** [comment]
> You might want to look for another set of roms in this case. Google "archive htgdb" and see what you find. Good luck ;)

Already using that one which is the crazy thing! Oh well, hope it gets sorted with the MRAs

**Comment by mrchrisster** [comment]
Ok strange. It might be worth a try to have the .neo files on SD and not CIFS to see if that works. That's all the suggestions I have at this point.
