### ISSUE TITLE
Sega CD games don't pass through the start menu

### ISSUE THREAD

**Issue by skooterblog** [mrchrisster/MiSTer_SAM#25]
Is it supposed to START the game automatically? 
Or am I supposed to use some hacked BIOS to launch the game automatically?

Thanks.

**Comment by mrchrisster** [comment]
Hey skooterblog, after loading a game into the MegaCD core it usually sits on the bios screen for an additional 5-10 seconds. After that it should autostart. It might be the bios you are using if it doesnt autostart. Best way to test is just load a chd file into the core and see what it does. I'm using a region free bios. If you google "mmmonkey megacd", you should find that bios...

**Comment by skooterblog** [comment]
Thank you. I was using the original US BIOS v2.0, it doesn't autostart. I got the same BIOS on its region-free version like you pointed out and it autostarts.

**Comment by mrchrisster** [comment]
That's good to know, we'll mention it in the readme
