### ISSUE TITLE
SAM is starting while update_all is running

### ISSUE THREAD

**Issue by skooterblog** [mrchrisster/MiSTer_SAM#27]
Shouldn't it check for this kind of activity? The script takes more than 2 minutes.

**Comment by mrchrisster** [comment]
Yep, it should. We figured out a way to make the script wait for update-all, it's just not implemented yet. Right now, update-all will still run in the background when SAM is starting up.

**Comment by mrchrisster** [comment]
Just as a note, SAM is also autostarting on top of when SAM is being launched manually

**Comment by mrchrisster** [comment]
SAM should now wait for update all to finish
