### ISSUE TITLE
8Bitdo USB wireless dongle not stopping cycling/loading of new Rom whilst using the controller.

### ISSUE THREAD

**Issue by CiREdrol** [mrchrisster/MiSTer_SAM#35]
I have a single controller connected 8bitdo dongle with a wireless SNES30 8bitdo controller. 

Picking up and playing a game doesn't break the reloading/cycling of a new rom. Rom loads while playing the game.

**Comment by mrchrisster** [comment]
Hey there,
please makes sure you're running the latest version by running `MiSTer_SAM_on.sh`. It will hopefully fix your issues since we found a bug in joystick detection

**Comment by CiREdrol** [comment]
Updated the core. This still occurs.

**Comment by mrchrisster** [comment]
Thanks, we're looking into it. Seems like the joysticks we tested are not a catch all scenario.

**Comment by mrchrisster** [comment]
We have found a solution to detect your joystick and will update SAM soon.

**Comment by mrchrisster** [comment]
I'll close this issue as it doubles up with another one
