### ISSUE TITLE
Reboot not working

### ISSUE THREAD

**Issue by CruelTott** [mrchrisster/MiSTer_SAM#37]
I noticed I could no longer use "reboot" from the command line to reboot my MiSTer when SAM is active.

I believe this is somehow caused by the infinite loop in S93mistersam preventing the the boot-sequence of the mister from finishing.

Would it be possible to move the loop out to a separate file that the init-script just starts in the background?

**Comment by mrchrisster** [comment]
Yeah, definitely not great to have our daemon run in an infinite while loop. We have it fixed in our testing branch with reboot working so this will be fixed as soon as we iron out all the other bugs.

**Comment by Mellified** [comment]
I went though and split the daemon process and the functional code in the `test` branch. Unfortunately `reboot` still hangs, while `reboot -f` works. More investigation to be done.

**Comment by mrchrisster** [comment]
this seems to be cifs related. when unmounting cifs before reboot, it works for us.
