### ISSUE TITLE
Minimize child processes

### ISSUE THREAD

**Issue by Mellified** [mrchrisster/MiSTer_SAM#46]
Currently SAM spawns a number of processes, several of which spawn their own child processes. This can be seen using `ps -o pid,ppid,args` via ssh. Ideally we can minimize the child processes to reduce SAM's footprint.

**Comment by mrchrisster** [comment]
Optimized SAM by making all button detection scripts python based. No more xxd or hexdump child processes.
Also using tmux now which cuts down forther on the process clutter. Stop command now closes SAM cleanly.
I think we can consider this optimized enough!
