### ISSUE TITLE
SAM apparently deleted all my GBA games

### ISSUE THREAD

**Issue by skooterblog** [mrchrisster/MiSTer_SAM#47]
I have my MiSTer running live for the past 11 hours (https://www.youtube.com/watch?v=9_0ls78LtP4) and I noticed that it is loading the same GBA game over and over. So I checked the GBA game folder and the only file is ~~~.gba. So apparently, SAM deleted all my GBA files.

**Comment by mrchrisster** [comment]
The way SAM works is by mounting a temporary file over your directory. Reboot will clear it.
