### ISSUE TITLE
After interrupting cycle by playing a game, the auto-switching doesn't resume.

### ISSUE THREAD

**Issue by mawk** [mrchrisster/MiSTer_SAM#59]
Currently I just have a bluetooth controller that I've been using. When I  interrupt the SAM cycle, I connect it, play something, and then disconnect the bluetooth controller when I'm done playing. However, at this point the SAM cycle does not resume. Any thoughts as to why that may be?

I've got these settings in the MiSTer_SAM.ini:

# Time before Super Attract Mode starts in seconds
# 300 = 5 minutes, 600 = 10 minutes, 900 = 15 minutes
samtimeout=60

# Time before going to the next core in seconds
gametimer=120

I've likely missed the info somewhere, but is there someplace where I can find a log on the SAM's activity? I'd gladly provide that if there is. Thanks!

**Comment by Mellified** [comment]
This is the expected default behavior. SAM starts only from the main MiSTer menu. If you want to change this there is an INI option you can set: `menuonly="Off"`

This was made the default because some folks were losing game progress when they left the MiSTer for a while.
