### ISSUE TITLE
I just love this attract mode!

### ISSUE THREAD

**Issue by kaz321123** [mrchrisster/MiSTer_SAM#71]
I'm sure there will be updates to add other cores in the future.

I'm trying to make a sorta 'pac-man pack', so the attract mode shows just pac-man games across the different cores.

Is there any sorta easy way I can get it to load let's say:  Atari 2600 games?  The Atari 2600 menu seems similar to others.

Love the work!  Such a cool feature, keep up the awesome work!

**Comment by mrchrisster** [comment]
hey kaz,
right now we don't have 2600 implemented but we might add some more cores in a future update. The way it works is simple:
Create a custom list for arcade games (mralist="/media/fat/Scripts/MiSTer_SAM_mras.txt" in `MiSTer_SAM.ini`)
and for the other cores, just change the custom directory for the games at the bottom `MiSTer_SAM.ini` to wherever you have your ini games.

**Comment by kaz321123** [comment]
Thanks so much for the reply.

I got the supported cores all working great with custom directories (and a list for arcade).  So the 'pac-man pack' is working fine! :)

I will be watching closely for any future updates, so I can add to my pack! :)
