### ISSUE TITLE
CPS only attract mode

### ISSUE THREAD

**Issue by thehughhefner** [mrchrisster/MiSTer_SAM#76]
Hi,
The Super attract mode is amazing and good job.

Would it be possible to include an option to only "play" CPS titles aka CPS1, CPS 1,5 and soon to come CPS2?

Kind regards

**Comment by Mellified** [comment]
Yes! You'll need to do:
1. Create a list of the MRA files you want to play with one per line and save it to `/media/fat/Scripts/` as `MiSTer_SAM_mras.txt`.
2. Edit the file `/media/fat/Scripts/MiSTer_SAM.ini`.
3. Find this line:
`#mralist="/media/fat/Scripts/MiSTer_SAM_mras.txt"`
4. Change it to remove the `#` at the front, so the line reads:
`mralist="/media/fat/Scripts/MiSTer_SAM_mras.txt"`

Reboot your MiSTer. Your arcade games should now cycle only the games you included!

Note that if your MRA files are in sub-directories of `/media/fat/_Arcade` you'll need to include that portion of the path. You can look at `/tmp/.SAMmras` after SAM has run to see an example file, or look at this example `MiSTer_SAM_mras.txt`:
```
Street Fighter Alpha 2 (Euro 960229).mra
Street Fighter Alpha 3 (Euro 980904).mra
Street Fighter Alpha Warriors Dreams (Euro 950727).mra
Street Fighter Zero 2 Alpha (Japan 960805).mra
Super Gem Fighter Mini Mix (USA 970904).mra
Super Puzzle Fighter II Turbo (Euro 960529).mra
Vampire Savior The Lord of Vampire (Euro 970519).mra
The Speed Rumbler (set 1).mra
Crush Roller.mra
X-Men Children of the Atom (Euro 950331).mra
X-Men Vs. Street Fighter (Euro 961004).mra
Vindicators Part II (rev 3).mra
Super Pacman.mra
Cyberbots Fullmetal Madness (Euro 950424).mra
Marvel Super Heroes (Euro 951024).mra
Marvel Super Heroes Vs. Street Fighter (Euro 970625).mra
Marvel Vs. Capcom Clash of Super Heroes (Euro 980123).mra
Vampire Hunter 2 Darkstalkers Revenge (Japan 970929).mra
Vampire Savior 2 The Lord of Vampire (Japan 970913).mra
King And Balloon (Japan).mra
Super Street Fighter II The New Challengers (World 931005).mra
Super Street Fighter II Turbo (World 940223).mra
```
