### ISSUE TITLE
Super attract cant see any games in my bfolders

### ISSUE THREAD

**Issue by peanutmans** [mrchrisster/MiSTer_SAM#77]
Hi Running SAM on fails to load roms I Have my rom folders on root of SD card but have sup folders for my roms I think that may be causing a issue Ive attached how my sub folders look and also the edited ini.
[SAM issue.zip](https://github.com/mrchrisster/MiSTer_SAM/files/6517402/SAM.issue.zip)

**Comment by Mellified** [comment]
Looking at your INI file there seems to be something wrong with it towards the bottom. Please delete it and run `MiSTer_SAM_on.sh`. Wait for the script to self-update and it should get you a new INI.

ROMs are usually found in `/media/fat/games/` rather than `/media/fat/` where you have them. That may be confusing SAM. If you can suggest you move your ROM folders into the appropriate folders under `/media/fat/games/`.

**Comment by peanutmans** [comment]
> 
> 
> Looking at your INI file there seems to be something wrong with it towards the bottom. Please delete it and run `MiSTer_SAM_on.sh`. Wait for the script to self-update and it should get you a new INI.
> 
> ROMs are usually found in `/media/fat/games/` rather than `/media/fat/` where you have them. That may be confusing SAM. If you can suggest you move your ROM folders into the appropriate folders under `/media/fat/games/`.
> 
> Let us know how it goes!

Hi ive had issues with the games folder that's why my games are not in that folder.


What do you mean by something wrong with the ini ?

**Comment by mrchrisster** [comment]
```
# GitHub branch to download updates from
# Valid choices are: "main" or "test"
#branch="test"
y useful via ssh
#samquiet="No"
#samdebug="Yes"
```
it says `y useful via ssh` in your ini, not sure what happened there?
Officially we only support games in `/media/fat/games`
You can try and change directories in the ini under `Game Paths`

**Comment by peanutmans** [comment]
I saw that yes should i just # that line out ?

**Comment by mrchrisster** [comment]
As Mellified suggested, start with a fresh ini, do your edits and try it out. 
We haven't tested `/media/fat` folder but it should work. Also change `corelist` to `corelist="gba"` for example. Try one system first and see if it works.

**Comment by peanutmans** [comment]
![1621554158049](https://user-images.githubusercontent.com/3714612/119062036-a99cec80-b9cd-11eb-89ef-9655787ef4ec.jpg) hi tried both those  im getting this error "paths mus precede expression 

is 
gbapath="/media/fat/GBA"
genesispath="/media/fat/Genesis"
megacdpath="/media/fat/MEGACD"
neogeopath="/media/fat/neogeo"
nespath="/media/fat/NES"
snespath="/media/fat/SNES"
tgfx16path="/media/fat/TGFX16"
tgfx16cdpath="/media/fat/TGFX16-CD"


how the rom paths should look ?

**Comment by Mellified** [comment]
The Update_MiSTer_BIOS.sh error indicates you have old updater files in the scripts directory. We’re not sure why, but they cause a conflict. Since that file doesn’t work anymore you can safely delete it. Things should start working then.

**Comment by peanutmans** [comment]
Yes that fixed it not sure if it will help you but before I saw this message, I ran the script via ssh and it worked fine before deleting the Update script
