### ISSUE TITLE
Update to latest MBC release (save file and save state support)

### ISSUE THREAD

**Issue by InquisitiveCoder** [mrchrisster/MiSTer_SAM#81]
There's a new release of MBC that [fixes save files and save states not working properly when games are loaded through MBC](https://github.com/pocomane/MiSTer_Batch_Control/issues/15). This is pretty inconvenient for SAM since you might lose your progress if you start playing a game that SAM loaded, and some GBA games don't go into attract mode if there's no save data (e.g. Golden Sun asks you to name the protagonist, Sonic Advance prompts you to choose your language.)

I'm not sure how much your fork of MBC has diverged from upstream but it'd be great to get this change merged into SAM officially. I've updated the `mbc` executable in my SAM installation and there don't seem to be any problems.

**Comment by mrchrisster** [comment]
Sorry for the late reply and thanks for finding this bug, I'll take a look at it. Should be easy to implement since we just changed some system names from the mbc code.

**Comment by mrchrisster** [comment]
Do you mind testing this?
Replace
```
mbcurl="blob/master/mbc_v03"
```
with
```
mbcurl="blob/master/mbc_v05"
```

**Comment by InquisitiveCoder** [comment]
I wasn't able to get SAM to download the new MBC by modifying the script. I think whenever I ran the script it would re-download its unmodified version from Github and use v03.

After manually downloading the file from [this url](https://github.com/mrchrisster/MiSTer_Batch_Control/blob/master/mbc_v05) and overwriting the executable in `Scripts/.MiSTer_SAM`, everything seems to be working as expected. I can see the ROM's original file name in the OSD instead of `~~~` as it's being loaded, and the save files are being recognized.

Thanks for the quick fix. I'll leave this open so you can close it once `MiSTer_SAM_on.sh` is updated with the new mbc URL, but as far as I can tell the issue is resolved.

**Comment by mrchrisster** [comment]
If you run ```MiSTer_SAM_on.sh``` it should install the new mbc now
