### ISSUE TITLE
Does not work with subfolders

### ISSUE THREAD

**Issue by damdai** [mrchrisster/MiSTer_SAM#82]
Looks like script will only work with game files in the root core directory.
Fixed by removing all instances of "-maxdepth 1" from script.
Was this intentional for some reason?

**Comment by mrchrisster** [comment]
Thanks dmdai. There was a reason for doing maxdepth for some of the simulated use cases we had during debugging. Neither mellified or myslef can remember why though. Do you mind creating a PR?
