### ISSUE TITLE
Does not work with directories containing too many files

### ISSUE THREAD

**Issue by damdai** [mrchrisster/MiSTer_SAM#83]
If a core game directory contains more than 2000 files or so (maybe less), will always load the first game in the directory even though it says it is loading a different game.

**Comment by mrchrisster** [comment]
Thanks for the bug report, we noticed this as well and looked into it a while back. Not quite sure what is causing it tbh

**Comment by mrchrisster** [comment]
Please don't have folders with that many files if you use SAM
