### ISSUE TITLE
Mega CD does not work properly

### ISSUE THREAD

**Issue by rhester72** [mrchrisster/MiSTer_SAM#84]
Not sure if it's a recent-ish (past few weeks, it seems) change to MiSTer Main or the MegaCD core, but the " !MBC" folder in /mister/fat/Games/MegaCD isn't being cleaned up properly after runs and thus tends to run the same title over and over again.  This is *not* observed with TGFX16-CD.

**Comment by mrchrisster** [comment]
Thanks for the bug report. Do you mind telling pocomane about it? He's the author of MBC that we use for loading games https://www.google.com/url?sa=t&source=web&rct=j&url=https://github.com/pocomane/MiSTer_Batch_Control&ved=2ahUKEwio1c_PltnyAhV1LH0KHeAECx8QFnoECAkQAQ&usg=AOvVaw3sXzMdgNtHCBhmVlV8qCT0

**Comment by rhester72** [comment]
Reported here: https://github.com/pocomane/MiSTer_Batch_Control/issues/16

**Comment by rhester72** [comment]
Another observation of the same issue:

https://misterfpga.org/viewtopic.php?p=32933#p32933

**Comment by mrchrisster** [comment]
so it seems like using mbc_v04 from `https://github.com/mrchrisster/MiSTer_Batch_Control` fixes megacd

**Comment by rhester72** [comment]
This appears to be resolved here:

https://github.com/pocomane/MiSTer_Batch_Control/commit/98c2fae2f1fb616ad094bebcab07551f3578f94b

**Comment by mrchrisster** [comment]
Please update MiSTer_SAM by running `MiSTer_SAM_on.sh update`
