### ISSUE TITLE
Integrate installation files with the MiSTer Downloader

### ISSUE THREAD

**Issue by theypsilon** [mrchrisster/MiSTer_SAM#87]
Since a couple of days ago, the Downloader now supports custom databases. This feature allows you to provide a new way for your users to get all the files they need for installing and keeping up-to-date MiSTer SAM. This new way would be integrated in the Downloader, the tool that they already use for installing and updating everything else.

The only thing you would need to do is to publish a json file containing the links to all the required MiSTer SAM files.

Here is an example of how the tty2oled project published their own database for installing their script:
![image](https://user-images.githubusercontent.com/852246/140665424-6f49b0fa-264e-43ac-8f38-8575bb757e3a.png)
[*Link to the json file.*](https://github.com/venice1200/MiSTer_tty2oled/blob/main/tty2oleddb.json)

You could create a similar one for MiSTer SAM.

Here is the documentation for creating your own custom database: https://github.com/MiSTer-devel/Downloader_MiSTer/blob/main/docs/custom-databases.md

When you publish it, I could add an option in update_all to integrate your MiSTer SAM database within the Misc menu, like I did for the tty2oled project:
![image](https://user-images.githubusercontent.com/852246/140665975-b907d9c6-3a03-4732-b019-930e789ea639.png)

**Comment by mrchrisster** [comment]
That sounds great thanks! We'll take a look at it.

**Comment by mrchrisster** [comment]
Here is the JSON file:
https://github.com/mrchrisster/MiSTer_SAM/blob/main/MiSTer_SAMdb.json

Hope this works and thanks!

**Comment by theypsilon** [comment]
Thanks a lot!

Just to clarify, this will download the file MiSTer_SAM_on.sh to people's Scripts/update_MiSTer_SAM.sh

This won't run any sub-script, but after this, people will see and will be able to run update_MiSTer_SAM in their Scripts menu.

I've just tested and worked fine :)

![image](https://user-images.githubusercontent.com/852246/140831408-231d938e-7e61-4b1c-895f-e598bd9a6917.png)

Feel free to add more files to that database, that way you can simplify the updating process of MiSTer_SAM

I'll be adding an option to Update All soon.

**Comment by mrchrisster** [comment]
Sounds good, thanks for thinking of us. We're thrilled to be accessible through your Downloader and thanks for all your work on it!
