### ISSUE TITLE
Stuck on Core Select Screen - Genesis and SNES & Game Selection seems not so random.

### ISSUE THREAD

**Issue by thesunnymachine** [mrchrisster/MiSTer_SAM#89]
I am having 2 issues that I cannot seem to fix.  Even when starting fresh with the ini file. 

When I have SNES and Genesis in my console option list, sometimes when switching cores/game it gets stuck on the core selection screen and never loads a game. 

I have only seen it hang on SNES and Genesis. 

The second issue is I keep getting the same games in my early rotation of cores.  Zombie Nation on NES is always loaded as the first NES game, and usually the first game I ever see.  In fact the NES core launches first with Zombie Nation so much it's what make it clear there's an issue. 

Sometimes it gets stuck on a game and won't move on.  Every Issue is present in this video:  [https://www.youtube.com/watch?v=xFG_WLEioFs](https://www.youtube.com/watch?v=xFG_WLEioFs)

For the most part if I disable SNES and Genesis, things run smoothly, but I still see a lot of the same games in early rotation.

**Comment by mrchrisster** [comment]
Hey there thanks for using SAM. This is probably an issue related to your roms.. are you using zipped packs?
You can google "htgb archive gamepacks" to get a supported pack. Hope this helps

**Comment by mrchrisster** [comment]
Did you have a chance to check if it's your game packs causing this?
