### ISSUE TITLE
Custom paths seem broken

### ISSUE THREAD

**Issue by jb242** [mrchrisster/MiSTer_SAM#9]
1) Changed "corelist" in the .ini to snes only
2) Changed "snespath" to reflect my setup (/media/fat/SNES)
3) Ran MiSTer_SAM_on.sh and waited 5 mins.

Attract mode starts, but pulls games from the Arcade directory.

1) Reverted "snespath" to default
2) Moved my SNES dir to /media/fat/games/SNES
3) Rebooted MiSTer, waited 5 mins

Attract mode now starts and pulls games from the SNES dir as expected.

**Comment by jb242** [comment]
Additional info -

Even with the default SNES path, the script still pulls arcade cores at random mixed in with the SNES ROMs.

**Comment by mrchrisster** [comment]
Yep, it was - and I believe we fixed the issue now.
Could you please update to the new version by running `/media/fat/Scripts/MiSTer_SAM_on.sh` and let us know if it works now?

**Comment by jb242** [comment]
Updated and tested. It's now hitting /media/fat/SNES correctly and seemingly not trying to load arcade cores, but is confused by directory depth.

In my case, I have a zip archive with SNES ROMs sorted into alphabetical subdirs. The Script tries to load a ROM, but hangs at the top level and eventually tries again in an endless loop.

**Comment by mrchrisster** [comment]
I noticed the same thing on my test setup. This is actually a problem with mbc (Mister Batch Control) that we are using to load roms. We will file an issue with the developer. 
For some reason having your directory in the /media/fat/Games subdirectory should make it work.

**Comment by jb242** [comment]
Yep, moving to /media/fat/games/SNES fixed it.

That's OK. It's time changed to the current standard anyway.  Thanks.

**Comment by mrchrisster** [comment]
ok, i'll close this issue now. thanks again for taking the time to report your issue.
