### ISSUE TITLE
Skip macOS metadata files

### ISSUE THREAD

**Issue by XAMPPRocky** [mrchrisster/MiSTer_SAM#97]
Hey, I've been trying this out on my MiSTer, and it's really cool, however I've noticed that some games are sometimes not working, and it appears to be because it ends up with a `._` prefixed in the filename, just from watching the output.

### Example Output

```
 List of cores is now: arcade gba genesis megacd  nes snes tgfx16 tgfx16cd
 Starting now on the MiSTer Arcade: Food Fight (Rev 3)
 Starting now on the MiSTer Arcade: Sea Wolf (Set 1)
 Starting now on the Nintendo Game Boy Advance: ._Kururin Paradise (Japan)
 ```

**Comment by rgdelato** [comment]
Not sure if this helps, but Mac adds hidden metadata files with this prefix and so it's very likely that your folder actually does have a file named `._Kururin Paradise (Japan)` in it.

As a workaround, I used an app called BlueHarvest to automatically remove the metadata files from my SD card, not sure if there are free alternatives that do the same thing.

**Comment by XAMPPRocky** [comment]
@rgdelato Thank you for your reply! That does indeed seem to be the case, thanks for letting me know, I've removed all that metadata and remember that next time I use the finder. It would be nice then, if `MiSTer_SAM` automatically (or as an option) ignored `._` prefixed files.

**Comment by mrchrisster** [comment]
For unpacked files I extended the find command to ignore hidden files. (files that start with a ".")
