### ISSUE TITLE
Passing multiple systems as arguments causes early termination

### ISSUE THREAD

**Issue by XAMPPRocky** [mrchrisster/MiSTer_SAM#98]
When you pass multiple system arguments to `MiSTer_SAM_on.sh`, the script will terminate early without actually running.

## Example (non-working) Output

```
/media/fat/Scripts/MiSTer_SAM_on.sh arcade gba
 MiSTer Arcade selected!
 Nintendo Game Boy Advance selected!
```

## Example (working) Output

```
/media/fat/Scripts/MiSTer_SAM_on.sh arcade
 MiSTer Arcade selected!
 Stopping other running instances of MiSTer_SAM_on.sh... Done!
 Let Mortal Kombat begin!
 Starting now on the MiSTer Arcade: Block Gal
```

**Comment by Mellified** [comment]
This is a known limitation. SAM will handle multiple command line arguments, but not multiple systems on the command line.
